## 📊 **PROYECTO FINAL DE ANÁLISIS DE DATOS**

**Curso:** Análisis de Datos Intermedio

**Docente:** Feibert Alirio Guzmán Pérez

**Autores:**

Bryan Emanuel Cadena Hincapie

Carlos Eduardo Bustamante

David Galvan Sierra

Luis Fernando Bermudez

# **"Análisis de correlación entre la calidad del aire y la tasa de mortalidad por enfermedades respiratorias en los departamentos de Colombia, 2024"**

# 📚 **Introducción**

La **calidad del aire** se define como el estado de la atmósfera según la concentración de contaminantes como **el ozono (O3)**, **el dióxido de nitrógeno (NO2)**, **el monóxido de carbono (CO)** y, especialmente, **el material particulado grueso (PM10)** y **fino (PM2.5)**. Estos contaminantes, son generados principalmente por el transporte, la industria y la quema de biomasa o combustibles fósiles. Debido a su tamaño, estas partículas sobre todo las **PM2.5** pueden penetrar profundamente en los pulmones e incluso ingresar al torrente sanguíneo, a diferencia de la **PM10** que se depositan principalmente en las vías respiratorias superiores, como la nariz, la garganta y los bronquios. En consecuencia, su exposición se relaciona con un mayor riesgo de desarrollar **enfermedades respiratorias** como enfermedad pulmonar obstructiva crónica (EPOC), infecciones respiratorias, disminución de la función pulmonar y agravamiento del asma, conllevando aun incremento en la **tasa de mortalidad por enfermedades respiratorias**.


En este contexto, Colombia enfrenta retos importantes con respecto a la gestión de la calidad del aire; de hecho, en 2023 el país se ubicó en el puesto 75 a nivel mundial, lo que evidencia una presión significativa de origen antropogénico. Y por otra parte, el monitoreo atmosférico realizado por el Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM), han reportado focos críticos de contaminación con un promedio de **PM2.5** de 14,1 μg/m³ en regiones urbanas como Antioquia, Córdoba y Magdalena.


Asimismo, esta problemática puede tener implicaciones directas en la salud pública, según el Departamento Administrativo Nacional de Estadística (DANE), indican aproximadamente 14.825 muertes anuales en el país. Ante este escenario, resulta necesario analizar la relación entre **la contaminación atmosférica** y **la tasa de mortalidad por enfermedades respiratorias**. Por ello, este estudio busca evaluar la posible **correlación entre las concentraciones de contaminantes (entre ellos los niveles de PM2.5 y PM10) por departamento y las muertes por causas respiratorias en 2024**, integrando información de la IDEAM y el DANE, con el fin de aportar evidencia para la formulación de políticas públicas en salud y gestión ambiental.

### ❓ **Planteamiento del problema**

A pesar de que Colombia cuenta con un Sistema de Vigilancia de la Calidad del Aire (SVCA) robusto liderado por el **IDEAM**, existe una contradicción alarmante entre los reportes de cumplimiento técnico y las estadísticas vitales de la población. Aunque el promedio nacional de $PM_{2.5}$ en zonas urbanas se sitúa cerca de los 14,1 $\mu g/m^3$, esta cifra es insuficiente para explicar la saturación de los servicios de salud por patologías obstructivas y alérgicas en departamentos específicos. El problema no radica únicamente en la presencia del contaminante, sino en la exposición crónica y desigual que enfrentan los ciudadanos en regiones de alta presión industrial y vehicular.

### ❗ **Justificación**

La presente investigación surge de la necesidad imperativa de articular la vigilancia ambiental con la realidad epidemiológica de Colombia en 2024, resolviendo la desconexión técnica que hoy impide conocer el impacto directo de los contaminantes en la salud. Mediante un análisis integrado y multivariado, este estudio trasciende la simple medición química al cruzar los registros de $PM_{2.5}$ y $PM_{10}$ con las cifras de defunción del **DANE** por departamento.

Por lo tanto, esta evidencia estadística permitirá determinar **si la mortalidad respiratoria responde a picos de contaminación aguda o a una exposición persistente**, proporcionando una base científica para reevaluar si los umbrales permisibles actuales son realmente efectivos para proteger la vida humana.

### 📋 **Pregunta de Investigación**

¿Existe una correlación estadísticamente significativa entre la calidad del aire y la tasa de mortalidad por enfermedades respiratorias en los departamentos de Colombia durante 2024?"

### 🎯 **Objetivo General**

  - **Determinar** la correlación estadística entre **la calidad del aire y la tasa de mortalidad por enfermedades respiratorias en los departamentos de Colombia durante 2024**, mediante la integración de bases de datos del IDEAM y el DANE, procesamiento con SQL y Pandas, y visualización interactiva, con el fin de generar evidencia para la toma de decisiones en políticas de salud ambiental.




---




  ### 🎯 **Objetivos Especificos**

  -	**Diseñar** una base de datos que integre la información de **la calidad del aire recuperada de la (IDEAM) y la tasa de mortalidad por enfermedades respiratorias en los departamentos de Colombia durante 2024 recuperada del DANE**, con el fin de habilitar a futuro las consultas complejas y los análisis estadísticos para evaluar la correlación entre contaminantes y la tasa de mortalidad por enfermedades respiratorias de Colombia durante 2024.

  - **Procesar** los datos de calidad del aire y mortalidad mediante integración de consultas avanzadas en SQL e integrarlos en Pandas, habilitando el análisis estadístico requerido para evaluar la relación entre **la calidad del aire y la tasa de mortalidad por enfermedades respiratorias en los departamentos de Colombia durante 2024**.

  - **Evaluar** la existencia de una correlación estadísticamente significativa entre **la calidad del aire y la tasa de mortalidad por enfermedades respiratorias en los departamentos de Colombia durante 2024**, mediante pruebas de correlación y un análisis exploratorio (EDA) con Pandas, con el fin de validar o refutar la hipótesis de asociación entre la contaminación atmosférica y la tasa de mortalidad por enfermedades respiratorias de Colombia durante 2024.

  - **Crear** un dashboard interactivo mediante Streamlit o Google Looker que visualice los resultados del análisis correlacional entre **la calidad del aire y la tasa de mortalidad por enfermedades respiratorias en los departamentos de Colombia durante 2024**, con el fin de facilitar la interpretación de hallazgos y apoyar la toma de decisiones en salud ambiental.

  - **Proponer** soluciones basadas en los hallazgos del análisis correlacional entre **la calidad del aire y la tasa de mortalidad por enfermedades respiratorias en los departamentos de Colombia durante 2024**, formulando recomendaciones para la gestión ambiental y sanitaria en los departamentos de Colombia, con el fin de documentar el impacto potencial de estas intervenciones y respaldar la toma de decisiones en políticas públicas.

# **Metodología**

##  **1.ETL**

##  **1.1 Extración de datos**

### **A) Datos del DANE**

Los datos de **la tasa de mortalidad por enfermedades respiratorias en Colombia durante el 2024**, fueron obtenidos a traves de la pagina oficial del **DANE:** (https://microdatos.dane.gov.co/index.php/catalog/878/get-microdata).

In [ ]:
# Cargar librería de Pandas
import pandas as pd


data_link = "https://drive.google.com/file/d/1-sLlaSMeg6A0TfRfATszCZGRfFjG9-PW/view?usp=drive_link"

file_id = data_link.split("/d/")[1].split("/")[0]
ruta_main = f"https://drive.google.com/uc?id={file_id}"

df = pd.read_csv(ruta_main, encoding='latin1', sep=',', low_memory=False)

print('✅ Dataframe cargado correctamente')
print('Shape:', df.shape)

✅ Dataframe cargado correctamente
Shape: (275778, 61)

Información general sobre el dataframe del **DANE** (Sin realizar el proceso de **ETL** aún), cuenta con **61 variables** y **275778 registros**.

In [ ]:
# Exploración inicial
print("Shape:", df.shape)
print("\nColumnas:", df.columns.tolist())
print("\nPrimeras filas:")

print("✅ Se cargo la exploración inicial del dataframe correctamente")

Shape: (275778, 61)

Columnas: ['COD_DPTO', 'COD_MUNIC', 'A_DEFUN', 'SIT_DEFUN', 'OTRSITIODE', 'TIPO_DEFUN', 'ANO', 'MES', 'HORA', 'MINUTOS', 'CODPAISNACFAL', 'SEXO', 'EST_CIVIL', 'GRU_ED1', 'GRU_ED2', 'NIVEL_EDU', 'ULTCURFAL', 'MUERTEPORO', 'SIMUERTEPO', 'OCUPACION', 'IDPERTET', 'CODPRES', 'CODPTORE', 'CODMUNRE', 'AREA_RES', 'SEG_SOCIAL', 'P_PMAN_IRIS', 'CONS_EXP', 'MU_PARTO', 'T_PARTO', 'TIPO_EMB', 'T_GES', 'T_GES_AGRU_CIE', 'PESO_NAC', 'CODPAISNACMAD', 'EDAD_MADRE', 'N_HIJOSV', 'N_HIJOSM', 'EST_CIVM', 'NIV_EDUM', 'ULTCURMAD', 'REGSOCIALMADRE', 'EMB_FAL', 'EMB_SEM', 'EMB_MES', 'CODOCUR', 'CODMUNOC', 'C_MUERTE', 'C_MUERTEB', 'C_MUERTEC', 'C_MUERTED', 'C_MUERTEE', 'C_MUERTEF', 'C_MUERTEG', 'ASIS_MED', 'CAUSA_MULT', 'C_BAS1', 'CAUSA_667', 'IDPROFCER', 'CAU_HOMOL', 'TIPOFORMULARIO']

Primeras filas:
✅ Se cargo la exploración inicial del dataframe correctamente

In [ ]:
df.head()

,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,OTRSITIODE,TIPO_DEFUN,ANO,MES,HORA,MINUTOS,...,C_MUERTEE,C_MUERTEF,C_MUERTEG,ASIS_MED,CAUSA_MULT,C_BAS1,CAUSA_667,IDPROFCER,CAU_HOMOL,TIPOFORMULARIO
0,73,854,3,3,NaN,2,2024,8,NaN,NaN,...,NaN,NaN,NaN,2,I219*F03,I219,303,1,51,1
1,11,1,1,1,NaN,2,2024,9,0.0,12.0,...,NaN,NaN,NaN,1,C833*I10 E119,C833,213,1,36,1
2,63,1,9,2,NaN,2,2024,11,0.0,0.0,...,NaN,NaN,NaN,2,R572/Z998/J189/S097 W55,W559,510,1,105,1
3,11,1,1,1,NaN,2,2024,9,1.0,40.0,...,NaN,NaN,NaN,1,R578/I639/I10*E039 E119 E785,I639,307,1,55,1
4,23,1,1,1,NaN,2,2024,10,2.0,39.0,...,NaN,NaN,NaN,1,R001/G909/C189*N19,G909,604,1,47,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275778 entries, 0 to 275777
Data columns (total 61 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   COD_DPTO        275778 non-null  int64
 1   COD_MUNIC       275778 non-null  int64
 2   A_DEFUN         275778 non-null  int64
 3   SIT_DEFUN       275778 non-null  int64
 4   OTRSITIODE      7713 non-null    object
 5   TIPO_DEFUN      275778 non-null  int64
 6   ANO             275778 non-null  int64
 7   MES             275778 non-null  int64
 8   HORA            268273 non-null  float64
 9   MINUTOS         268273 non-null  float64
 10  CODPAISNACFAL   236617 non-null  float64
 11  SEXO            275778 non-null  int64
 12  EST_CIVIL       275778 non-null  int64
 13  GRU_ED1         275778 non-null  int64
 14  GRU_ED2         275778 non-null  int64
 15  NIVEL_EDU       275778 non-null  int64
 16  ULTCURFAL       275778 non-null  int64
 17  MUERTEPORO      269777 non-null  float64
 18  SIMUERTEPO      101 non-null     float64
 19  OCUPACION       13481 non-null   object
 20  IDPERTET        275778 non-null  int64
 21  CODPRES         272058 non-null  float64
 22  CODPTORE        271191 non-null  float64
 23  CODMUNRE        271191 non-null  float64
 24  AREA_RES        271210 non-null  float64
 25  SEG_SOCIAL      275778 non-null  int64
 26  P_PMAN_IRIS     275778 non-null  int64
 27  CONS_EXP        275778 non-null  int64
 28  MU_PARTO        4759 non-null    float64
 29  T_PARTO         4759 non-null    float64
 30  TIPO_EMB        4759 non-null    float64
 31  T_GES           4759 non-null    float64
 32  T_GES_AGRU_CIE  4759 non-null    float64
 33  PESO_NAC        4759 non-null    float64
 34  CODPAISNACMAD   4371 non-null    float64
 35  EDAD_MADRE      4759 non-null    float64
 36  N_HIJOSV        4759 non-null    float64
 37  N_HIJOSM        4759 non-null    float64
 38  EST_CIVM        4759 non-null    float64
 39  NIV_EDUM        4759 non-null    float64
 40  ULTCURMAD       4759 non-null    float64
 41  REGSOCIALMADRE  4759 non-null    float64
 42  EMB_FAL         16570 non-null   float64
 43  EMB_SEM         16482 non-null   float64
 44  EMB_MES         16337 non-null   float64
 45  CODOCUR         31621 non-null   float64
 46  CODMUNOC        31621 non-null   float64
 47  C_MUERTE        38093 non-null   float64
 48  C_MUERTEB       207916 non-null  float64
 49  C_MUERTEC       52027 non-null   float64
 50  C_MUERTED       105117 non-null  float64
 51  C_MUERTEE       7210 non-null    float64
 52  C_MUERTEF       820 non-null     float64
 53  C_MUERTEG       53 non-null      float64
 54  ASIS_MED        275778 non-null  int64
 55  CAUSA_MULT      275778 non-null  object
 56  C_BAS1          275778 non-null  object
 57  CAUSA_667       275778 non-null  int64
 58  IDPROFCER       275778 non-null  int64
 59  CAU_HOMOL       275778 non-null  int64
 60  TIPOFORMULARIO  275778 non-null  int64
dtypes: float64(35), int64(22), object(4)
memory usage: 128.3+ MB

### **B) Datos del IDEAM**

Los datos de calidad de aire de la **IDEAM** para el 2024, no se encuentran disponibles a nivel de departamentos. Por ende, se optara por usar *"datos dummy"*.
Primero que todo se trabajara con datos de **contaminantes ambientales**, utilizados para representar la **calidad del aire** como los siguientes:

| Contaminante atmosférico (Nombre y Símbolo) | Umbrales de Concentración y Clasificación (IQA) |
| :--- | :--- |
| **Material Particulado PM2.5**<br>*(Material particulado fino)* | **0.0 – 12.0** → IQA 0-50 (Bueno)<br>**12.1 – 37.0** → IQA 51-100 (Aceptable)<br>**37.1 – 55.0** → IQA 101-150 (Dañino grupos sensibles)<br>**55.1 – 150.0** → IQA 151-200 (Dañino)<br>**150.1 – 250.0** → IQA 201-300 (Muy dañino)<br>**250.1 – 500.0** → IQA 301-500 (Peligroso) |
| **Material Particulado PM10**<br>*(Material particulado grueso)* | **0 – 54** → IQA 0-50 (Bueno)<br>**55 – 154** → IQA 51-100 (Aceptable)<br>**155 – 254** → IQA 101-150 (Dañino grupos sensibles)<br>**255 – 354** → IQA 151-200 (Dañino)<br>**355 – 424** → IQA 201-300 (Muy dañino)<br>**425 – 604** → IQA 301-500 (Peligroso) |
| **Dióxido de Nitrógeno (NO₂)** | **0 – 53** → IQA 0-50 (Bueno)<br>**54 – 100** → IQA 51-100 (Aceptable)<br>**101 – 360** → IQA 101-150 (Dañino grupos sensibles)<br>**361 – 649** → IQA 151-200 (Dañino)<br>**650 – 1249** → IQA 201-300 (Muy dañino)<br>**1250 – 2049** → IQA 301-500 (Peligroso) |
| **Dióxido de Azufre (SO₂)** | **0 – 35** → IQA 0-50 (Bueno)<br>**36 – 75** → IQA 51-100 (Aceptable)<br>**76 – 185** → IQA 101-150 (Dañino grupos sensibles)<br>**186 – 304** → IQA 151-200 (Dañino)<br>**305 – 604** → IQA 201-300 (Muy dañino)<br>**605 – 1004** → IQA 301-500 (Peligroso) |
| **Monóxido de Carbono (CO)** | **0.0 – 4.4** → IQA 0-50 (Bueno)<br>**4.5 – 9.4** → IQA 51-100 (Aceptable)<br>**9.5 – 12.4** → IQA 101-150 (Dañino grupos sensibles)<br>**12.5 – 15.4** → IQA 151-200 (Dañino)<br>**15.5 – 30.4** → IQA 201-300 (Muy dañino)<br>**30.5 – 50.4** → IQA 301-500 (Peligroso) |
| **Ozono (O₃)** | **0 – 54** → IQA 0-50 (Bueno)<br>**55 – 70** → IQA 51-100 (Aceptable)<br>**71 – 85** → IQA 101-150 (Dañino grupos sensibles)<br>**86 – 105** → IQA 151-200 (Dañino)<br>**106 – 200** → IQA 201-300 (Muy dañino)<br>**201 – 404** → IQA 301-500 (Peligroso) |

***NOTA:***   Seguidamente, se construyeron otras tablas con *datos dummy* que nos permitieron construir la tabla de el **índice de calidad de aire** esencial para este estudio. Adicionalmente, se construyeron otras tablas complementarias para facilitar la obtención de el **índice de calidad de aire**, y al mismo tiempo mantener coherencia y realismo en el ejercicio, y fueron las siguientes: **medición de la calidad del aire** y **estaciones de monitoreo**.

*(Más adelante se dará más información acerca de la creación de las tablas en el siguiente apartado)*

## **1.2. Transformación de datos**

A partir de la primera tabla presentada en el estudio, considerada como una **tabla integral**, se generaron diversas subtablas con el propósito de organizar la información en estructuras más específicas según las variables contenidas. Esta descomposición permitió estructurar adecuadamente la información para la construcción de una base de datos en MySQL y, posteriormente, facilitar el desarrollo del **Modelo Entidad–Relación** y del **Modelo Relacional**.

No obstante, previo a este proceso, fue necesario crear una columna de **identificadores únicos (ID)** generados de forma aleatoria en la tabla integral, garantizando que no se repitieran y que se mantuvieran dentro de un rango numérico previamente definido, y asi **identificar de forma única cada registro**. Y, subsecuentemente, se realizo una **limpieza de datos y filtrar los mismos.**

### **A) Creación de IDs**

In [ ]:
# Importar Librerias de trabajo

# Manejo de datos
import pandas as pd
import numpy as np

print("✅ Librerias cargadas correctamente")

✅ Librerias cargadas correctamente

In [ ]:
# Verificar que el número de filas no supere el rango disponible
rango_disponible = 9999999 - 10000 + 1  # 9.990.000 IDs disponibles
print(f"Filas en el dataset: {len(df):,}")
print(f"Rango disponible de IDs: {rango_disponible:,}")

#Agregar una semilla
np.random.seed(42)

# Generar IDs únicos aleatorios dentro del rango
ids = np.random.choice(range(10000, 10000000), size=len(df), replace=False)

# Insertar como primera columna
df.insert(0, 'ID', ids)

# Verificar resultado
print("\n¿IDs únicos?", df['ID'].is_unique)
print(df[['ID']].head(10))

print("✅ Se agregaron los ID correctamente")

Filas en el dataset: 275,778
Rango disponible de IDs: 9,990,000

¿IDs únicos? True
        ID
0   411195
1   618864
2   721440
3   740610
4  1586788
5  1981119
6  7846882
7  2199906
8  1716762
9  8092821
✅ Se agregaron los ID correctamente

In [ ]:
# Verificar que se hayan agregado las ID
df.head()

,ID,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,OTRSITIODE,TIPO_DEFUN,ANO,MES,HORA,...,C_MUERTEE,C_MUERTEF,C_MUERTEG,ASIS_MED,CAUSA_MULT,C_BAS1,CAUSA_667,IDPROFCER,CAU_HOMOL,TIPOFORMULARIO
0,411195,73,854,3,3,NaN,2,2024,8,NaN,...,NaN,NaN,NaN,2,I219*F03,I219,303,1,51,1
1,618864,11,1,1,1,NaN,2,2024,9,0.0,...,NaN,NaN,NaN,1,C833*I10 E119,C833,213,1,36,1
2,721440,63,1,9,2,NaN,2,2024,11,0.0,...,NaN,NaN,NaN,2,R572/Z998/J189/S097 W55,W559,510,1,105,1
3,740610,11,1,1,1,NaN,2,2024,9,1.0,...,NaN,NaN,NaN,1,R578/I639/I10*E039 E119 E785,I639,307,1,55,1
4,1586788,23,1,1,1,NaN,2,2024,10,2.0,...,NaN,NaN,NaN,1,R001/G909/C189*N19,G909,604,1,47,1

### **B) Limpieza y filtrado de datos**

Para garantizar la calidad de los datos, se implementó un procedimiento sistemático de manejo de valores faltantes. Inicialmente, se cuantificó la proporción de *valores nulos* por variable en la **tabla integral**, identificando **las columnas con mayor tasa de ausencia de datos**. Posteriormente, se aplicaron filtros a las variables, **eliminando únicamente aquellas variables que sean redundantes o no utiles en nuestro estudio.**

 De modo que se garantice preservar los registros con mayor completitud de datos por variable.

In [ ]:
# # Verificar que columnas tiene mas datos nulos de la tabla integral
null_counts = df.isnull().sum().sort_values(ascending=False)

print("Columna con más datos nulos:")
display(null_counts.head(61))

print("✅ Se todas las columnas con sus respectivos datos nulos correctamente")

Columna con más datos nulos:

C_MUERTEG        275725
SIMUERTEPO       275677
C_MUERTEF        274958
CODPAISNACMAD    271407
ULTCURMAD        271019
                  ...
CAUSA_MULT            0
C_BAS1                0
CAUSA_667             0
IDPROFCER             0
CAU_HOMOL             0
Length: 61, dtype: int64

✅ Se todas las columnas con sus respectivos datos nulos correctamente

In [ ]:
# Lista de columnas que se eliminarán en función de la cantidad de valores nulos.
columns_to_drop = [
    'C_MUERTEG', 'C_MUERTEF', 'CODPAISNACMAD',
    'ULTCURMAD', 'MU_PARTO', 'TIPO_EMB', 'T_GES',
    'PESO_NAC', 'T_GES_AGRU_CIE', 'T_PARTO', 'NIV_EDUM',
    'EST_CIVM', 'N_HIJOSM', 'N_HIJOSV', 'EDAD_MADRE',
    'REGSOCIALMADRE', 'C_MUERTEE', 'OTRSITIODE', 'MINUTOS', 'HORA', 'C_MUERTEB',
    'C_MUERTE', 'EMB_MES', 'EMB_SEM', 'EMB_FAL', 'C_MUERTEC', 'C_MUERTED', 'CODPRES',
    'SIMUERTEPO'
]

# Recargar el CSV para recuperar todas las columnas antes de filtrar
df = pd.read_csv(ruta, encoding='latin1', sep=',', low_memory=False)

# Reinsertar los IDs generados previamente
df.insert(0, 'ID', ids)

# Eliminar columnas
df = df.drop(columns=columns_to_drop, errors='ignore')

print(f'✅ Columnas eliminadas. Nueva dimensión: {df.shape}')
display(df[['ID', 'AREA_RES']].head())

✅ Columnas eliminadas. Nueva dimensión: (275778, 33)

        ID  AREA_RES
0   411195       3.0
1   618864       1.0
2   721440       1.0
3   740610       1.0
4  1586788       1.0

Se eliminaron 29 columnas o variables con mayor cantidad de **datos nulos**.

In [ ]:
# Verificar los valores o datos nulos de las columnas filtradas de la nueva tabla integral
null_counts = df.isnull().sum().sort_values(ascending=False)

print(f"✅ Nuevo dataframe integral generado correctamente")
print(f"Nuevas columnas con más datos nulos:")
print(null_counts.head(31))

✅ Nuevo dataframe integral generado correctamente
Nuevas columnas con más datos nulos:
OCUPACION        262297
CODMUNOC         244157
CODOCUR          244157
CODPAISNACFAL     39161
MUERTEPORO         6001
CODPTORE           4587
CODMUNRE           4587
AREA_RES           4568
ID                    0
MES                   0
ANO                   0
SEXO                  0
COD_DPTO              0
SIT_DEFUN             0
TIPO_DEFUN            0
A_DEFUN               0
COD_MUNIC             0
NIVEL_EDU             0
ULTCURFAL             0
GRU_ED1               0
GRU_ED2               0
EST_CIVIL             0
IDPERTET              0
P_PMAN_IRIS           0
SEG_SOCIAL            0
CONS_EXP              0
ASIS_MED              0
CAUSA_MULT            0
C_BAS1                0
CAUSA_667             0
IDPROFCER             0
dtype: int64

**Excepciones de columnas a no excluir:**  OCUPACION, CODOCUR y CODMUNOC.

| Variables a **NO** excluir | Descripción (Diccionario DANE) |
| :--- | :--- |
| **OCUPACION** | **Ocupación habitual.**<br>Se refiere al nombre de la ocupación, oficio o profesión que desempeñaba habitualmente la persona fallecida.|
| **CODOCUR** | **Código del Departamento de Ocurrencia.**<br>Corresponde al código numérico (según la división político-administrativa DIVIPOLA) del departamento donde ocurrió el hecho vital (la defunción o el nacimiento). |
| **CODMUNOC** | **Código del Municipio de Ocurrencia.**<br>Corresponde al código numérico (DIVIPOLA) del municipio donde ocurrió el hecho vital. |

Subsecuentemente, se eliminaron **las columnas consideradas irrelevantes o redundantes**, garantizando que **la tabla integral filtrada contuviera únicamente las variables críticas para el análisis posterior.**


| Variables excluidas | Descripción (Diccionario DANE) |
| :--- | :--- |
| **ULTCURFAL** | **Último grado de escolaridad cursado por el fallecido.**<br>Se refiere al nivel educativo más alto alcanzado por la persona fallecida (ej. Ninguno, Preescolar, Primaria, Secundaria, Técnica, Universitario, Postgrado). |
| **IDPERTET** | **Pertenencia étnica.**<br>Identifica si la persona fallecida se autorreconoció como perteneciente a un grupo étnico específico (Indígena, Rom/Gitano, Raizal del archipiélago, Palenquero de San Basilio, Afrocolombiano/Afrodescendiente, Ninguno de los anteriores). |
| **CONS_EXP** | **Consultó al médico durante la última enfermedad.**<br>Indica si el fallecido recibió atención médica o consultó a un profesional de la salud durante el proceso de la enfermedad que causó su muerte (Valores: 1=Si, 2=No, 9=Ignorado). |
| **ASIS_MED** | **Asistencia médica al fallecer.**<br>Indica si la persona recibió atención médica en el momento exacto de su muerte (distingue de la consulta previa; se refiere a la atención final). |
| **CAUSA_MULT** | **Causas múltiples de muerte.**<br>Corresponde al conjunto de enfermedades, lesiones o complicaciones que condujeron a la muerte. Incluye la causa directa, las antecedentes o intermedias y la causa básica, generalmente codificadas según la CIE-10. |
| **IDPROFCER** | **Identificación del profesional que certifica la defunción.**<br>Número de identificación (Tarjeta Profesional o Cédula) del médico o personal autorizado que firmó el certificado de defunción. |
| **CAU_HOMOL** | **Causa básica de muerte homologada.**<br>Es la causa de muerte final asignada después del proceso de codificación y validación por parte del DANE. Es la enfermedad o lesión que inició la cadena de acontecimientos patológicos que condujeron directamente a la muerte, estandarizada para análisis estadístico. |
|**TIPOFORMULARIO** | **Fuente del Certificado.** <br> Tipo de formulario para la captura de información.    
|**TIPO_DEFUN** |  **Tipo de defunción.** <br> El documento solo presenta un tipo de defuncion (
2= Defunción no fetal), lo cual es redundante para el estudio, ya que todos estos datos son defunciones no fetales.

In [ ]:
# Filtrado de columnas irrelevantes y redundantes
columns_to_drop = [
      'ULTCURFAL', 'IDPERTET','CONS_EXP', 'ASIS_MED', 'CAUSA_MULT', 'IDPROFCER',
      'CAU_HOMOL', 'TIPOFORMULARIO',
      # 'TIPO_DEFUN'
]

# Eliminar columnas de la tabla integral (df)
df = df.drop(columns=columns_to_drop, errors='ignore')

print(f"✅ Se eliminaron {len(columns_to_drop)} columnas correctamente.")
print(f"Nueva dimensión del dataframe: {df.shape}")
display(df.head())

✅ Se eliminaron 8 columnas correctamente.
Nueva dimensión del dataframe: (275778, 25)

,ID,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,TIPO_DEFUN,ANO,MES,CODPAISNACFAL,SEXO,...,OCUPACION,CODPTORE,CODMUNRE,AREA_RES,SEG_SOCIAL,P_PMAN_IRIS,CODOCUR,CODMUNOC,C_BAS1,CAUSA_667
0,411195,73,854,3,3,2,2024,8,170.0,2,...,NaN,73.0,854.0,3.0,2,0,NaN,NaN,I219,303
1,618864,11,1,1,1,2,2024,9,170.0,1,...,NaN,11.0,1.0,1.0,2,0,NaN,NaN,C833,213
2,721440,63,1,9,2,2,2024,11,NaN,1,...,NaN,63.0,594.0,1.0,1,2,63.0,1.0,W559,510
3,740610,11,1,1,1,2,2024,9,170.0,2,...,NaN,11.0,1.0,1.0,2,0,NaN,NaN,I639,307
4,1586788,23,1,1,1,2,2024,10,170.0,1,...,CONDUCTORES DE MOTOCICLETAS,23.0,1.0,1.0,2,0,NaN,NaN,G909,604

Se eliminaron 9 columnas o variables **irrelevantes o redundantes**.

In [ ]:
# Verificar las columnas irrelevantes o redundantes filtradas de la nueva tabla integral
print(f"✅ Nuevo dataframe integral generado correctamente")
print(df.info(24))

✅ Nuevo dataframe integral generado correctamente
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275778 entries, 0 to 275777
Data columns (total 25 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ID             275778 non-null  int64
 1   COD_DPTO       275778 non-null  int64
 2   COD_MUNIC      275778 non-null  int64
 3   A_DEFUN        275778 non-null  int64
 4   SIT_DEFUN      275778 non-null  int64
 5   TIPO_DEFUN     275778 non-null  int64
 6   ANO            275778 non-null  int64
 7   MES            275778 non-null  int64
 8   CODPAISNACFAL  236617 non-null  float64
 9   SEXO           275778 non-null  int64
 10  EST_CIVIL      275778 non-null  int64
 11  GRU_ED1        275778 non-null  int64
 12  GRU_ED2        275778 non-null  int64
 13  NIVEL_EDU      275778 non-null  int64
 14  MUERTEPORO     269777 non-null  float64
 15  OCUPACION      13481 non-null   object
 16  CODPTORE       271191 non-null  float64
 17  CODMUNRE       271191 non-null  float64
 18  AREA_RES       271210 non-null  float64
 19  SEG_SOCIAL     275778 non-null  int64
 20  P_PMAN_IRIS    275778 non-null  int64
 21  CODOCUR        31621 non-null   float64
 22  CODMUNOC       31621 non-null   float64
 23  C_BAS1         275778 non-null  object
 24  CAUSA_667      275778 non-null  int64
dtypes: float64(7), int64(16), object(2)
memory usage: 52.6+ MB
None

Seguidamente, se realizó un filtrado inteligente de los datos con respecto a la variable **"P_PMAN_IRIS"**.


| Variable a filtrar todos los datos | Descripción (Diccionario DANE) |
| :--- | :--- |
| **P_PMAN_IRIS** | **Probable manera de muerte (IRIS).**<br>Tipo de defunción según la naturaleza externa o circunstancia que originó el evento de muerte, distinguiendo entre causas naturales y causas externas |


Por lo tanto, con el propósito de garantizar la validez interna del estudio, se restringió el conjunto de datos a las defunciones de causa natural **(código = 0)**, **descartando aquellos registros correspondientes a muertes por causas externas.** Este criterio de selección permitió aislar el efecto de las enfermedades respiratorias como variable de resultado, evitando que eventos no relacionados con la exposición a contaminantes atmosféricos introdujeran ruido o confusión en la estimación de la correlación.

In [ ]:
# Filtrar todos los registros para que únicamente se extraigan los datos con P_PMAN_IRIS = 0
print(f"Registros antes del filtrado: {len(df):,}")

df = df[df['P_PMAN_IRIS'] == 0].copy()

print(f"✅ Filtrado completado. Registros con P_PMAN_IRIS = 0: {len(df):,}")
display(df.head())

Registros antes del filtrado: 275,778
✅ Filtrado completado. Registros con P_PMAN_IRIS = 0: 240,327

,ID,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,TIPO_DEFUN,ANO,MES,CODPAISNACFAL,SEXO,...,OCUPACION,CODPTORE,CODMUNRE,AREA_RES,SEG_SOCIAL,P_PMAN_IRIS,CODOCUR,CODMUNOC,C_BAS1,CAUSA_667
0,411195,73,854,3,3,2,2024,8,170.0,2,...,NaN,73.0,854.0,3.0,2,0,NaN,NaN,I219,303
1,618864,11,1,1,1,2,2024,9,170.0,1,...,NaN,11.0,1.0,1.0,2,0,NaN,NaN,C833,213
3,740610,11,1,1,1,2,2024,9,170.0,2,...,NaN,11.0,1.0,1.0,2,0,NaN,NaN,I639,307
4,1586788,23,1,1,1,2,2024,10,170.0,1,...,CONDUCTORES DE MOTOCICLETAS,23.0,1.0,1.0,2,0,NaN,NaN,G909,604
5,1981119,8,1,1,1,2,2024,10,170.0,2,...,NaN,8.0,1.0,1.0,2,0,NaN,NaN,G938,604

Y, por último, se filtraron los ***valores nulos*** de toda la **tabla integral**, garantizando que los registros retenidos contuvieran información completa en las variables críticas para el análisis.

### **C) Creación de nuevos dataframes a partir de la tabla integral filtrada**

Posteriormente, se llevó a cabo el proceso de descomposición de la **tabla integral** en múltiples **tablas especializadas**. Cada tabla resultante fue estructurada para contener atributos relacionados con un área específica del dominio de análisis, **garantizando así la coherencia de los datos y reduciendo redundancias o datos no relevantes en nuestro estudio.**

La **primera tabla especializada** creada fue la tabla **persona**, donde se recopila **la información basica de la persona fallecida**.

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero) |
| **id_pais_nacimiento** |`int64` (Entero) |
| **sexo** | `int64` (Entero) |
| **grupo_edad_1** | `int64` (Entero) |
| **grupo_edad_2** | `int64` (Entero) |
| **estado_civil** | `int64` (Entero) |
| **nivel_educativo** | `int64` (Entero) |
| **seguridad_social** | `int64` (Entero) |
| **ocupacion** | `object` (String) |

In [ ]:
# Cargar libreria
import pandas as pd

# Crear nuevo dataframe 'persona' con las columnas mapeadas
persona = pd.DataFrame({
    'id':                df['ID'],#PK
    'id_pais_nacimiento': df['CODPAISNACFAL'].astype(pd.Int64Dtype()), # Cambiado a Int64 para manejar nulos, no es una FK
    'sexo':              df['SEXO'],
    'grupo_edad_1':      df['GRU_ED1'],
    'grupo_edad_2':      df['GRU_ED2'],
    'estado_civil':      df['EST_CIVIL'],
    'nivel_educativo':   df['NIVEL_EDU'],
    'seguridad_social':  df['SEG_SOCIAL'],
    'ocupacion':         df['OCUPACION'].astype(str).str.strip()
})

# Verificación
print("Shape:", persona.shape)
print("\nTipos de datos:")
print(persona.dtypes)
print("\nPrimeras filas:")
persona.head()

Shape: (240327, 9)

Tipos de datos:
id                     int64
id_pais_nacimiento     Int64
sexo                   int64
grupo_edad_1           int64
grupo_edad_2           int64
estado_civil           int64
nivel_educativo        int64
seguridad_social       int64
ocupacion             object
dtype: object

Primeras filas:

,id,id_pais_nacimiento,sexo,grupo_edad_1,grupo_edad_2,estado_civil,nivel_educativo,seguridad_social,ocupacion
0,411195,170,2,26,6,6,2,2,nan
1,618864,170,1,22,6,6,2,2,nan
3,740610,170,2,22,6,6,13,2,nan
4,1586788,170,1,20,5,6,99,2,CONDUCTORES DE MOTOCICLETAS
5,1981119,170,2,22,6,9,99,2,nan

La **segunda tabla especializada** creada fue la tabla **tiempo**, donde se recopila **la información con respecto al tiempo de defunción**.


| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero) |
| **anio** | `int64` (Entero) |
| **mes** | `int64` (Entero) |

In [ ]:
# ============================================================
# PASO 1: Crear la tabla 'tiempo'
# Extraemos combinaciones únicas de año y mes del dataset original
# para evitar redundancia (un solo registro por combinación)
# ============================================================
tiempo = df[['A_DEFUN', 'MES']].drop_duplicates().reset_index(drop=True)

# Generamos un ID autoincremental starting en 1
tiempo.insert(0, 'id', range(1, len(tiempo) + 1))

# Renombramos las columnas al estándar de la tabla destino
tiempo.rename(columns={'A_DEFUN': 'anio', 'MES': 'mes'}, inplace=True)

print("Tabla tiempo creada:")
print(tiempo)


# ============================================================
# PASO 2: Crear la tabla 'defuncion' con id_tiempo como None
# (placeholder temporal hasta hacer el join con tabla tiempo)
# ============================================================
defuncion = pd.DataFrame({
    'id':                      df['ID'],           # Llave primaria
    'id_persona':              df['ID'],           # FK hacia tabla persona (relación 1 a 1)
    'id_tiempo':               df['ID'],               # FK hacia tabla tiempo (se asigna en PASO 3)
    'id_municipio_ocurrencia': df['CODMUNOC'].astype(str).str.strip(),  # FK hacia tabla municipio
    'id_municipio_residencia': df['CODMUNRE'].astype(str).str.strip(),  # FK hacia tabla municipio
    'area_defuncion':          df['A_DEFUN'],      # 1=Cabecera, 2=Centro poblado, 3=Rural, 9=Sin info
    'area_residencia':         df['AREA_RES'],     # Área de residencia del fallecido
    'sitio_defuncion':         df['SIT_DEFUN'],    # 1=Hospital, 2=Centro salud, 3=Casa, etc.
    'probable_manera_muerte':  df['MUERTEPORO'],   # Manera probable de muerte
    'tipo_accidente_laboral':  df['TIPO_DEFUN']    # Tipo de defunción / accidente laboral
})


# ============================================================
# PASO 3: Agregar columnas auxiliares de año y mes al dataframe
# original para poder hacer el join con la tabla tiempo
# ============================================================
df_temp = df[['ID', 'A_DEFUN', 'MES']].copy()
df_temp.rename(columns={'A_DEFUN': 'anio', 'MES': 'mes'}, inplace=True)


# ============================================================
# PASO 4: Hacer el join entre df_temp y tabla tiempo
# para obtener el id_tiempo correspondiente a cada registro
# ============================================================
df_temp = df_temp.merge(
    tiempo[['id', 'anio', 'mes']],  # Traemos solo las columnas necesarias de tiempo
    on=['anio', 'mes'],             # Unimos por año y mes
    how='left'                      # Left join para conservar todos los registros originales
).rename(columns={'id': 'id_tiempo'})


# ============================================================
# PASO 5: Asignar el id_tiempo correcto a la tabla defuncion
# haciendo merge con el resultado del paso anterior
# ============================================================
defuncion = defuncion.drop(columns=['id_tiempo'])  # Eliminamos el placeholder None

defuncion = defuncion.merge(
    df_temp[['ID', 'id_tiempo']],   # Solo necesitamos ID e id_tiempo
    left_on='id',                   # Unimos por el ID de defuncion
    right_on='ID',                  # Con el ID del dataframe temporal
    how='left'
).drop(columns=['ID'])              # Eliminamos columna duplicada ID del merge


# ============================================================
# PASO 6: Reordenar columnas para que id_tiempo quede
# en la posición correcta según el modelo de la tabla
# ============================================================
cols = [
    'id', 'id_persona', 'id_tiempo',
    'id_municipio_ocurrencia', 'id_municipio_residencia',
    'area_defuncion', 'area_residencia', 'sitio_defuncion',
    'probable_manera_muerte', 'tipo_accidente_laboral'
]
defuncion = defuncion[cols]


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
print("Shape tabla defuncion:", defuncion.shape)
print("\nValores nulos por columna:")
print(defuncion.isnull().sum())
print("\nPrimeras filas:")
defuncion.head()

Tabla tiempo creada:
    id  anio  mes
0    1     3    8
1    2     1    9
2    3     1   10
3    4     1   12
4    5     1    7
5    6     3   10
6    7     2   10
7    8     1    6
8    9     1   11
9   10     1    8
10  11     1    4
11  12     2    8
12  13     3    9
13  14     2    9
14  15     3   12
15  16     2   12
16  17     2    6
17  18     3    6
18  19     3   11
19  20     2   11
20  21     3    7
21  22     1    1
22  23     1    5
23  24     3    2
24  25     3    4
25  26     2    4
26  27     3    3
27  28     1    3
28  29     1    2
29  30     3    5
30  31     2    7
31  32     2    5
32  33     3    1
33  34     2    1
34  35     9   11
35  36     9    5
36  37     9   12
37  38     2    3
38  39     2    2
39  40     9    7
40  41     9    4
41  42     9    1
42  43     9    2
43  44     9    6
44  45     9    8
45  46     9   10
46  47     9    9
47  48     9    3
Shape tabla defuncion: (240327, 10)

Valores nulos por columna:
id                            0
id_persona                    0
id_tiempo                     0
id_municipio_ocurrencia       0
id_municipio_residencia       0
area_defuncion                0
area_residencia            2676
sitio_defuncion               0
probable_manera_muerte     5529
tipo_accidente_laboral        0
dtype: int64

Primeras filas:

,id,id_persona,id_tiempo,id_municipio_ocurrencia,id_municipio_residencia,area_defuncion,area_residencia,sitio_defuncion,probable_manera_muerte,tipo_accidente_laboral
0,411195,411195,1,nan,854.0,3,3.0,3,2.0,2
1,618864,618864,2,nan,1.0,1,1.0,1,2.0,2
2,740610,740610,2,nan,1.0,1,1.0,1,2.0,2
3,1586788,1586788,3,nan,1.0,1,1.0,1,2.0,2
4,1981119,1981119,3,nan,1.0,1,1.0,1,2.0,2

La **tercera tabla especializada** creada fue la tabla de **defunción**, donde se recopila la **información con respecto a la defunción de la persona o registro.**

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero) |
| **id_persona** | `int64` (Entero) |
| **id_tiempo** | `int64` (Entero) |
| **id_municipio_ocurrencia** | `object` (String / Código DIVIPOLA) |
| **id_municipio_residencia** | `object` (String / Código DIVIPOLA) |
| **area_defuncion** | `int64` (Entero) |
| **area_residencia** | `float64` (Decimal) |
| **sitio_defuncion** | `int64` (Entero) |
| **probable_manera_muerte** | `float64` (Decimal) |
| **ocupacion_causa_muerte** | `float64` (Decimal) |
| **tipo_accidente_laboral** | `int64` (Entero) |

In [ ]:
# Crear nuevo dataframe 'defuncion'
defuncion = pd.DataFrame({
    'id':                      df['ID'],
    'id_persona':              df['ID'], #FK
    'id_tiempo':               df['ID'],  # se asignar en el join con tabla tiempo#FK
    'municipio_ocurrencia': df['CODMUNOC'].astype(str).str.strip(),
    'municipio_residencia': df['CODMUNRE'].astype(str).str.strip(),
    'area_defuncion':          df['A_DEFUN'],
    'area_residencia':         df['AREA_RES'],
    'sitio_defuncion':         df['SIT_DEFUN'],
    'probable_manera_muerte':  df['MUERTEPORO'],
    'tipo_accidente_laboral':  df['TIPO_DEFUN']
})
# Verificacin
print("Shape:", defuncion.shape)
print("\nTipos de datos:")
print(defuncion.dtypes)
print("\nPrimeras filas:")
defuncion.head()

Shape: (240327, 10)

Tipos de datos:
id                          int64
id_persona                  int64
id_tiempo                   int64
municipio_ocurrencia       object
municipio_residencia       object
area_defuncion              int64
area_residencia           float64
sitio_defuncion             int64
probable_manera_muerte    float64
tipo_accidente_laboral      int64
dtype: object

Primeras filas:

,id,id_persona,id_tiempo,municipio_ocurrencia,municipio_residencia,area_defuncion,area_residencia,sitio_defuncion,probable_manera_muerte,tipo_accidente_laboral
0,411195,411195,411195,nan,854.0,3,3.0,3,2.0,2
1,618864,618864,618864,nan,1.0,1,1.0,1,2.0,2
3,740610,740610,740610,nan,1.0,1,1.0,1,2.0,2
4,1586788,1586788,1586788,nan,1.0,1,1.0,1,2.0,2
5,1981119,1981119,1981119,nan,1.0,1,1.0,1,2.0,2

La **cuarta tabla especializada** creada fue la tabla **causa de defunción**, donde se recopila la **información con respecto al motivo de defunción de la persona u registro según los codigos de causa básica CIE-10 y la lista OPS 667.**

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero) |
| **id_defuncion** | `int64` (Entero) |
| **codigo_cie10** | `object` (String) |
| **causa_ops_667** | `object` (String) |

In [ ]:
# ============================================================
# Crear la tabla 'causa_defuncion'
# Contiene los códigos de causa de muerte asociados a cada
# defunción usando la causa básica CIE-10 y la lista OPS 667
# ============================================================
causa_defuncion = pd.DataFrame({
    'id':            df['ID'],                                # Llave primaria
    'id_defuncion':  df['ID'],                                # FK hacia tabla defuncion (relación 1 a 1)
    'codigo_cie10':  df['C_BAS1'].astype(str).str.strip(),   # Causa básica de muerte en CIE-10
    'causa_ops_667': df['CAUSA_667'].astype(str).str.strip() # Causa de muerte en lista OPS 667
})

# Verificación
print("Shape:", causa_defuncion.shape)
print("\nValores nulos por columna:")
print(causa_defuncion.isnull().sum())
print("\nPrimeras filas:")
causa_defuncion.head()

Shape: (240327, 4)

Valores nulos por columna:
id               0
id_defuncion     0
codigo_cie10     0
causa_ops_667    0
dtype: int64

Primeras filas:

        id  id_defuncion codigo_cie10 causa_ops_667
0   411195        411195         I219           303
1   618864        618864         C833           213
3   740610        740610         I639           307
4  1586788       1586788         G909           604
5  1981119       1981119         G938           604

La **quinta tabla especializada** creada fue la tabla de **departamento**, donde se recopila la **información con respecto al departamento de defunción de la persona u registro.**

**NOTA:** Los departamentos se clasifican en 6 regiones de Colombia: Región Caribe, Región Eje Cafetero y Antioquia, Región Pacífica, Región Central, Región Llanos / Orinoquía y Región Amazonía.

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `object` (String / Código DIVIPOLA 2 dígitos) |
| **nombre** | `object` (String) |
| **region** | `object` (String) |

In [ ]:
# ============================================================
# PASO 1: Cargar el archivo Geoportal DIVIPOLA desde Drive
# header=1 porque los encabezados reales están en la fila 2 del Excel
# ============================================================

data_link_geo = "https://docs.google.com/spreadsheets/d/1VdwD5t0nPfZJhth8jYxBLVdQ59v9_Jta/edit?usp=drive_link&ouid=106561639823128853825&rtpof=true&sd=true"

file_id_geo = data_link_geo.split("/d/")[1].split("/")[0]
ruta_geo = f"https://drive.google.com/uc?id={file_id_geo}"

geo = pd.read_excel(ruta_geo, header=1)

# Estandarizamos código departamento
geo['Código Departamento'] = geo['Código Departamento'].astype(str).str.strip().str.zfill(2)

# Extraemos departamentos únicos
depto_raw = geo[['Código Departamento', 'Nombre Departamento']]\
            .drop_duplicates(subset='Código Departamento')\
            .reset_index(drop=True)

print('Departamentos únicos registrados:', depto_raw.shape[0])


# ============================================================
# PASO 2: Diccionario de regiones por departamento
# ============================================================
regiones = {
    '08': 'Región Caribe', '13': 'Región Caribe', '20': 'Región Caribe',
    '23': 'Región Caribe', '44': 'Región Caribe', '47': 'Región Caribe',
    '70': 'Región Caribe', '88': 'Región Caribe',
    '05': 'Región Eje Cafetero y Antioquia', '17': 'Región Eje Cafetero y Antioquia',
    '63': 'Región Eje Cafetero y Antioquia', '66': 'Región Eje Cafetero y Antioquia',
    '19': 'Región Pacífica', '27': 'Región Pacífica',
    '52': 'Región Pacífica', '76': 'Región Pacífica',
    '11': 'Región Central', '15': 'Región Central', '25': 'Región Central',
    '41': 'Región Central', '54': 'Región Central',
    '68': 'Región Central', '73': 'Región Central',
    '50': 'Región Llanos / Orinoquía', '81': 'Región Llanos / Orinoquía',
    '85': 'Región Llanos / Orinoquía', '86': 'Región Llanos / Orinoquía',
    '99': 'Región Llanos / Orinoquía',
    '18': 'Región Amazonía', '91': 'Región Amazonía', '94': 'Región Amazonía',
    '95': 'Región Amazonía', '97': 'Región Amazonía',
}


# ============================================================
# PASO 3: Construir la tabla 'departamento'
# ============================================================
departamento = pd.DataFrame({
    'id':     depto_raw['Código Departamento'],
    'nombre': depto_raw['Nombre Departamento'],
    'region': depto_raw['Código Departamento'].map(regiones)
}).reset_index(drop=True)


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
print('\nShape tabla departamento:', departamento.shape)
print('\nValores nulos por columna:')
print(departamento.isnull().sum())
print('\nDistribución por región:')
print(departamento['region'].value_counts())
print('\nPrimeras filas:')
departamento.head(10)

Departamentos únicos registrados: 33

Shape tabla departamento: (33, 3)

Valores nulos por columna:
id        0
nombre    0
region    0
dtype: int64

Distribución por región:
region
Región Caribe                      8
Región Central                     7
Región Llanos / Orinoquía          5
Región Amazonía                    5
Región Eje Cafetero y Antioquia    4
Región Pacífica                    4
Name: count, dtype: int64

Primeras filas:

   id         nombre                           region
0  05      ANTIOQUIA  Región Eje Cafetero y Antioquia
1  08      ATLÁNTICO                    Región Caribe
2  11  BOGOTÁ, D. C.                   Región Central
3  13        BOLÍVAR                    Región Caribe
4  15         BOYACÁ                   Región Central
5  17         CALDAS  Región Eje Cafetero y Antioquia
6  18        CAQUETÁ                  Región Amazonía
7  19          CAUCA                  Región Pacífica
8  20          CESAR                    Región Caribe
9  23        CÓRDOBA                    Región Caribe

La **sexta tabla especializada** creada fue la tabla de **pais**, donde se recopila la **información con respecto al país de nacimiento del fallecido.**

**NOTA:** Los códigos de país corresponden al estándar M49 de la ONU. Se incluyen 73 países únicos encontrados en el dataset del DANE.

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `object` (String / Código M49 ONU) |
| **nombre** | `object` (String) |

In [ ]:
# ============================================================
# PASO 1: Cargar la lista M49 oficial de la ONU
# Fuente: OMNIKA DataStore (repositorio oficial de UNSD)
# ============================================================
url_m49 = 'https://github.com/omnika-datastore/unsd-m49-standard-area-codes/raw/refs/heads/main/2022-09-24__CSV_UNSD_M49.csv'

m49_raw = pd.read_csv(url_m49, sep=';', encoding='utf-8')


# ============================================================
# PASO 2: Preparar la lista M49
# Solo necesitamos el código M49 y el nombre del país
# ============================================================
m49 = m49_raw[['M49 Code', 'Country or Area']].copy()
m49['M49 Code'] = m49['M49 Code'].astype(str).str.strip()


# ============================================================
# PASO 3: Extraer códigos únicos de país del dataset principal
# Eliminamos NaN y convertimos a string para el join
# ============================================================
paises_dane = df['CODPAISNACFAL'].dropna().unique()
paises_dane = pd.DataFrame({'codigo': paises_dane})
paises_dane['codigo'] = paises_dane['codigo'].astype(int).astype(str).str.strip()

print("Países en lista M49:", m49.shape[0])
print("Códigos únicos de país en DANE:", paises_dane.shape[0])


# ============================================================
# PASO 4: Join entre códigos DANE y lista M49
# para obtener el nombre oficial de cada país
# ============================================================
paises_raw = paises_dane.merge(
    m49,
    left_on='codigo',
    right_on='M49 Code',
    how='left'
)


# ============================================================
# PASO 5: Corregir país faltante
# Código 530 = Antillas Neerlandesas, disuelto en 2010
# No aparece en M49 actual pero el DANE aún lo referencia
# ============================================================
paises_raw.loc[paises_raw['codigo'] == '530', 'Country or Area'] = 'Netherlands Antilles'


# ============================================================
# PASO 6: Construir la tabla 'pais'
# ============================================================
pais = pd.DataFrame({
    'id':     paises_raw['codigo'],         # PK - Código M49
    'nombre': paises_raw['Country or Area'] # Nombre oficial ONU
}).reset_index(drop=True)


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
print("\nShape tabla pais:", pais.shape)
print("\nValores nulos por columna:")
print(pais.isnull().sum())
print("\nPrimeras filas:")
pais.head(10)

Países en lista M49: 249
Códigos únicos de país en DANE: 73

Shape tabla pais: (73, 2)

Valores nulos por columna:
id        0
nombre    0
dtype: int64

Primeras filas:

    id                              nombre
0  170                            Colombia
1  250                              France
2  862  Venezuela (Bolivarian Republic of)
3  156                               China
4  218                             Ecuador
5  340                            Honduras
6  530                Netherlands Antilles
7  840            United States of America
8  724                               Spain
9  214                  Dominican Republic

La **séptima tabla especializada** creada fue la tabla de **estaciones de monitoreo**, donde se recopila la **información de la ubicación geográfica, altitud y entidad operadora de cada estación de monitoreo.**

**NOTA:** Los nombres de las estaciones se basan en estaciones reales de monitoreo de calidad del aire en Colombia. Se crearon 61 estaciones distribuidas en las 6 regiones del país.

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero autoincremental) |
| **id_municipio** | `object` (String / Código DIVIPOLA 5 dígitos) |
| **nombre** | `object` (Texto) |
| **latitud** | `float64` (Decimal / Flotante) |
| **longitud** | `float64` (Decimal / Flotante) |
| **altitud** | `float64` (Decimal / Flotante) |
| **entidad_operadora** | `object` (Texto) |

In [ ]:
# Creación Dataframe: Estaciones de monitoreo

# ============================================================
# PASO 1: Definir estaciones de monitoreo dummy
# Se crean estaciones representativas por región
# usando coordenadas reales de municipios principales
# ============================================================

estaciones_data = [
    # -------------------------------------------------------
    # Región Caribe
    # -------------------------------------------------------
    {'id_municipio': '08001', 'nombre': 'Estación Barranquilla Norte',          'latitud': 11.0041,  'longitud': -74.8070, 'altitud': 18.0,   'entidad_operadora': 'IDEAM'},
    {'id_municipio': '08001', 'nombre': 'Estación Barranquilla Sur',            'latitud': 10.9878,  'longitud': -74.7893, 'altitud': 15.0,   'entidad_operadora': 'IDEAM'},
    {'id_municipio': '08001', 'nombre': 'Estación Barranquilla Puerto',         'latitud': 10.9605,  'longitud': -74.7965, 'altitud': 5.0,    'entidad_operadora': 'DAMA Atlántico'},
    {'id_municipio': '13001', 'nombre': 'Estación Cartagena Centro',            'latitud': 10.3910,  'longitud': -75.4794, 'altitud': 2.0,    'entidad_operadora': 'IDEAM'},
    {'id_municipio': '13001', 'nombre': 'Estación Cartagena Zona Industrial',   'latitud': 10.4061,  'longitud': -75.5100, 'altitud': 3.0,    'entidad_operadora': 'EPA Cartagena'},
    {'id_municipio': '47001', 'nombre': 'Estación Santa Marta Costera',         'latitud': 11.2408,  'longitud': -74.1990, 'altitud': 6.0,    'entidad_operadora': 'IDEAM'},
    {'id_municipio': '47001', 'nombre': 'Estación Santa Marta Sierra Nevada',   'latitud': 11.1647,  'longitud': -74.1153, 'altitud': 850.0,  'entidad_operadora': 'IDEAM'},
    {'id_municipio': '44001', 'nombre': 'Estación Riohacha Guajira',            'latitud': 11.5444,  'longitud': -72.9072, 'altitud': 4.0,    'entidad_operadora': 'IDEAM'},
    {'id_municipio': '44001', 'nombre': 'Estación Riohacha Costera',            'latitud': 11.5562,  'longitud': -72.9215, 'altitud': 2.0,    'entidad_operadora': 'CORPOGUAJIRA'},
    {'id_municipio': '23001', 'nombre': 'Estación Montería Sinú',               'latitud': 8.7575,   'longitud': -75.8876, 'altitud': 15.0,   'entidad_operadora': 'CVS'},
    {'id_municipio': '70001', 'nombre': 'Estación Sincelejo Sabanas',           'latitud': 9.3047,   'longitud': -75.3978, 'altitud': 213.0,  'entidad_operadora': 'IDEAM'},
    {'id_municipio': '20001', 'nombre': 'Estación Valledupar Central',          'latitud': 10.4631,  'longitud': -73.2532, 'altitud': 169.0,  'entidad_operadora': 'CORPOCESAR'},
    {'id_municipio': '88001', 'nombre': 'Estación San Andrés Isla',             'latitud': 12.5847,  'longitud': -81.7006, 'altitud': 3.0,    'entidad_operadora': 'IDEAM'},

    # -------------------------------------------------------
    # Región Eje Cafetero y Antioquia
    # -------------------------------------------------------
    {'id_municipio': '05001', 'nombre': 'Estación Medellín Área Metro',         'latitud': 6.2442,   'longitud': -75.5812, 'altitud': 1495.0, 'entidad_operadora': 'SIATA'},
    {'id_municipio': '05001', 'nombre': 'Estación Medellín Poblado',            'latitud': 6.2087,   'longitud': -75.5665, 'altitud': 1550.0, 'entidad_operadora': 'SIATA'},
    {'id_municipio': '05001', 'nombre': 'Estación Medellín Bello',              'latitud': 6.3352,   'longitud': -75.5569, 'altitud': 1450.0, 'entidad_operadora': 'SIATA'},
    {'id_municipio': '05001', 'nombre': 'Estación Medellín Itagüí',             'latitud': 6.1843,   'longitud': -75.5997, 'altitud': 1480.0, 'entidad_operadora': 'SIATA'},
    {'id_municipio': '05045', 'nombre': 'Estación Apartadó Urabá',              'latitud': 7.8826,   'longitud': -76.6275, 'altitud': 30.0,   'entidad_operadora': 'CORNARE'},
    {'id_municipio': '17001', 'nombre': 'Estación Manizales Central',           'latitud': 5.0703,   'longitud': -75.5138, 'altitud': 2153.0, 'entidad_operadora': 'IDEAM'},
    {'id_municipio': '17001', 'nombre': 'Estación Manizales Nevado Ruiz',       'latitud': 5.1011,   'longitud': -75.3232, 'altitud': 3800.0, 'entidad_operadora': 'SGC'},
    {'id_municipio': '63001', 'nombre': 'Estación Armenia Centro',              'latitud': 4.5339,   'longitud': -75.6811, 'altitud': 1483.0, 'entidad_operadora': 'CRQ'},
    {'id_municipio': '66001', 'nombre': 'Estación Pereira Urbana',              'latitud': 4.8133,   'longitud': -75.6961, 'altitud': 1411.0, 'entidad_operadora': 'IDEAM'},
    {'id_municipio': '66001', 'nombre': 'Estación Pereira Dosquebradas',        'latitud': 4.8391,   'longitud': -75.6697, 'altitud': 1390.0, 'entidad_operadora': 'CARDER'},

    # -------------------------------------------------------
    # Región Pacífica
    # -------------------------------------------------------
    {'id_municipio': '76001', 'nombre': 'Estación Cali Sur',                    'latitud': 3.4516,   'longitud': -76.5320, 'altitud': 1018.0, 'entidad_operadora': 'DAGMA'},
    {'id_municipio': '76001', 'nombre': 'Estación Cali Norte',                  'latitud': 3.4879,   'longitud': -76.5213, 'altitud': 1025.0, 'entidad_operadora': 'DAGMA'},
    {'id_municipio': '76001', 'nombre': 'Estación Cali Ladera',                 'latitud': 3.4612,   'longitud': -76.5601, 'altitud': 1200.0, 'entidad_operadora': 'CVC'},
    {'id_municipio': '76001', 'nombre': 'Estación Cali Yumbo Industrial',       'latitud': 3.5962,   'longitud': -76.4953, 'altitud': 970.0,  'entidad_operadora': 'CVC'},
    {'id_municipio': '27001', 'nombre': 'Estación Quibdó Río Atrato',           'latitud': 5.6947,   'longitud': -76.6611, 'altitud': 43.0,   'entidad_operadora': 'IDEAM'},
    {'id_municipio': '27001', 'nombre': 'Estación Quibdó Selva',                'latitud': 5.7105,   'longitud': -76.6401, 'altitud': 55.0,   'entidad_operadora': 'CODECHOCÓ'},
    {'id_municipio': '52001', 'nombre': 'Estación Pasto Volcán Galeras',        'latitud': 1.2136,   'longitud': -77.2811, 'altitud': 2527.0, 'entidad_operadora': 'SGC'},
    {'id_municipio': '52001', 'nombre': 'Estación Pasto Urbana',                'latitud': 1.2140,   'longitud': -77.2814, 'altitud': 2500.0, 'entidad_operadora': 'CORPONARIÑO'},
    {'id_municipio': '19001', 'nombre': 'Estación Popayán Central',             'latitud': 2.4448,   'longitud': -76.6147, 'altitud': 1702.0, 'entidad_operadora': 'CRC'},

    # -------------------------------------------------------
    # Región Central
    # -------------------------------------------------------
    {'id_municipio': '11001', 'nombre': 'Estación Bogotá Kennedy',              'latitud': 4.6097,   'longitud': -74.0817, 'altitud': 2600.0, 'entidad_operadora': 'RMCAB'},
    {'id_municipio': '11001', 'nombre': 'Estación Bogotá Usaquén',              'latitud': 4.7110,   'longitud': -74.0318, 'altitud': 2650.0, 'entidad_operadora': 'RMCAB'},
    {'id_municipio': '11001', 'nombre': 'Estación Bogotá Fontibón',             'latitud': 4.6740,   'longitud': -74.1469, 'altitud': 2548.0, 'entidad_operadora': 'RMCAB'},
    {'id_municipio': '11001', 'nombre': 'Estación Bogotá Suba',                 'latitud': 4.7417,   'longitud': -74.0840, 'altitud': 2580.0, 'entidad_operadora': 'RMCAB'},
    {'id_municipio': '11001', 'nombre': 'Estación Bogotá Puente Aranda',        'latitud': 4.6261,   'longitud': -74.1068, 'altitud': 2570.0, 'entidad_operadora': 'RMCAB'},
    {'id_municipio': '68001', 'nombre': 'Estación Bucaramanga Floridablanca',   'latitud': 7.1193,   'longitud': -73.1227, 'altitud': 959.0,  'entidad_operadora': 'IDEAM'},
    {'id_municipio': '68001', 'nombre': 'Estación Bucaramanga Norte',           'latitud': 7.1398,   'longitud': -73.1256, 'altitud': 980.0,  'entidad_operadora': 'CDMB'},
    {'id_municipio': '68001', 'nombre': 'Estación Bucaramanga Girón',           'latitud': 7.0742,   'longitud': -73.1681, 'altitud': 750.0,  'entidad_operadora': 'CDMB'},
    {'id_municipio': '54001', 'nombre': 'Estación Cúcuta Central',              'latitud': 7.8939,   'longitud': -72.5078, 'altitud': 320.0,  'entidad_operadora': 'CORPONOR'},
    {'id_municipio': '54001', 'nombre': 'Estación Cúcuta Villa del Rosario',    'latitud': 7.8321,   'longitud': -72.4734, 'altitud': 310.0,  'entidad_operadora': 'CORPONOR'},
    {'id_municipio': '73001', 'nombre': 'Estación Ibagué Centro',               'latitud': 4.4389,   'longitud': -75.2322, 'altitud': 1285.0, 'entidad_operadora': 'CORTOLIMA'},
    {'id_municipio': '73001', 'nombre': 'Estación Ibagué Zona Cafetera',        'latitud': 4.4612,   'longitud': -75.2541, 'altitud': 1320.0, 'entidad_operadora': 'CORTOLIMA'},
    {'id_municipio': '41001', 'nombre': 'Estación Neiva Huila',                 'latitud': 2.9273,   'longitud': -75.2819, 'altitud': 442.0,  'entidad_operadora': 'CAM'},
    {'id_municipio': '15001', 'nombre': 'Estación Tunja Boyacá',                'latitud': 5.5353,   'longitud': -73.3678, 'altitud': 2820.0, 'entidad_operadora': 'CORPOBOYACÁ'},
    {'id_municipio': '25001', 'nombre': 'Estación Agua de Dios Cundinamarca',   'latitud': 4.3772,   'longitud': -74.6697, 'altitud': 360.0,  'entidad_operadora': 'CAR'},

    # -------------------------------------------------------
    # Región Llanos / Orinoquía
    # -------------------------------------------------------
    {'id_municipio': '50001', 'nombre': 'Estación Villavicencio Llanos',        'latitud': 4.1420,   'longitud': -73.6266, 'altitud': 467.0,  'entidad_operadora': 'IDEAM'},
    {'id_municipio': '50001', 'nombre': 'Estación Villavicencio Piedemonte',    'latitud': 4.1698,   'longitud': -73.6489, 'altitud': 510.0,  'entidad_operadora': 'CORMACARENA'},
    {'id_municipio': '85001', 'nombre': 'Estación Yopal Casanare',              'latitud': 5.3378,   'longitud': -72.3959, 'altitud': 320.0,  'entidad_operadora': 'CORPORINOQUIA'},
    {'id_municipio': '85001', 'nombre': 'Estación Yopal Sabana',                'latitud': 5.3521,   'longitud': -72.4102, 'altitud': 315.0,  'entidad_operadora': 'IDEAM'},
    {'id_municipio': '81001', 'nombre': 'Estación Arauca Río Arauca',           'latitud': 7.0898,   'longitud': -70.7617, 'altitud': 125.0,  'entidad_operadora': 'CORPORINOQUIA'},
    {'id_municipio': '99001', 'nombre': 'Estación Puerto Carreño Vichada',      'latitud': 6.1891,   'longitud': -67.4836, 'altitud': 51.0,   'entidad_operadora': 'IDEAM'},
    {'id_municipio': '86001', 'nombre': 'Estación Mocoa Putumayo',              'latitud': 1.1522,   'longitud': -76.6483, 'altitud': 327.0,  'entidad_operadora': 'CORPOAMAZONIA'},

    # -------------------------------------------------------
    # Región Amazonía
    # -------------------------------------------------------
    {'id_municipio': '91001', 'nombre': 'Estación Leticia Amazónica',           'latitud': -4.1932,  'longitud': -69.9395, 'altitud': 82.0,   'entidad_operadora': 'IDEAM'},
    {'id_municipio': '91001', 'nombre': 'Estación Leticia Río Amazonas',        'latitud': -4.2012,  'longitud': -69.9301, 'altitud': 75.0,   'entidad_operadora': 'CORPOAMAZONIA'},
    {'id_municipio': '18001', 'nombre': 'Estación Florencia Caquetá',           'latitud': 1.6144,   'longitud': -75.6062, 'altitud': 242.0,  'entidad_operadora': 'CORPOAMAZONIA'},
    {'id_municipio': '18001', 'nombre': 'Estación Florencia Piedemonte',        'latitud': 1.6298,   'longitud': -75.5901, 'altitud': 280.0,  'entidad_operadora': 'IDEAM'},
    {'id_municipio': '94001', 'nombre': 'Estación Inírida Guainía',             'latitud': 3.8653,   'longitud': -67.9239, 'altitud': 96.0,   'entidad_operadora': 'CORPOAMAZONIA'},
    {'id_municipio': '95001', 'nombre': 'Estación San José Guaviare',           'latitud': 2.5684,   'longitud': -72.6416, 'altitud': 185.0,  'entidad_operadora': 'IDEAM'},
    {'id_municipio': '97001', 'nombre': 'Estación Mitú Vaupés',                 'latitud': 1.2530,   'longitud': -70.2331, 'altitud': 235.0,  'entidad_operadora': 'CORPOAMAZONIA'},
]


# ============================================================
# PASO 2: Construir el dataframe estacion_monitoreo
# El ID se genera como autoincremental desde 1
# ============================================================
estacion_monitoreo = pd.DataFrame(estaciones_data)
estacion_monitoreo.insert(0, 'id', range(1, len(estacion_monitoreo) + 1))


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
print("Shape tabla estacion_monitoreo:", estacion_monitoreo.shape)
print("\nValores nulos por columna:")
print(estacion_monitoreo.isnull().sum())
print("\nEstaciones por entidad operadora:")
print(estacion_monitoreo['entidad_operadora'].value_counts())
print("\nEstaciones por municipio:")
print(estacion_monitoreo['id_municipio'].value_counts())
print("\nPrimeras filas:")

print("✅ Dataframe generado correctamente")
estacion_monitoreo.head()

Shape tabla estacion_monitoreo: (61, 7)

Valores nulos por columna:
id                   0
id_municipio         0
nombre               0
latitud              0
longitud             0
altitud              0
entidad_operadora    0
dtype: int64

Estaciones por entidad operadora:
entidad_operadora
IDEAM             18
RMCAB              5
CORPOAMAZONIA      5
SIATA              4
SGC                2
CORPONOR           2
DAGMA              2
CDMB               2
CORPORINOQUIA      2
CORTOLIMA          2
CVC                2
CRQ                1
CVS                1
CORNARE            1
CORPOGUAJIRA       1
EPA Cartagena      1
DAMA Atlántico     1
CORPOCESAR         1
CORPONARIÑO        1
CRC                1
CARDER             1
CODECHOCÓ          1
CORPOBOYACÁ        1
CAM                1
CORMACARENA        1
CAR                1
Name: count, dtype: int64

Estaciones por municipio:
id_municipio
11001    5
05001    4
76001    4
08001    3
68001    3
13001    2
17001    2
66001    2
44001    2
47001    2
27001    2
18001    2
91001    2
50001    2
85001    2
73001    2
54001    2
52001    2
19001    1
63001    1
88001    1
23001    1
70001    1
20001    1
05045    1
41001    1
15001    1
25001    1
99001    1
81001    1
86001    1
94001    1
95001    1
97001    1
Name: count, dtype: int64

Primeras filas:
✅ Dataframe generado correctamente

,id,id_municipio,nombre,latitud,longitud,altitud,entidad_operadora
0,1,08001,Estación Barranquilla Norte,11.0041,-74.8070,18.0,IDEAM
1,2,08001,Estación Barranquilla Sur,10.9878,-74.7893,15.0,IDEAM
2,3,08001,Estación Barranquilla Puerto,10.9605,-74.7965,5.0,DAMA Atlántico
3,4,13001,Estación Cartagena Centro,10.3910,-75.4794,2.0,IDEAM
4,5,13001,Estación Cartagena Zona Industrial,10.4061,-75.5100,3.0,EPA Cartagena

In [ ]:
# Descargar dataframe: Estaciones de monitoreo
from google.colab import files

# --- CÓDIGO PARA DESCARGAR ---

# 1. Guardamos el dataframe en un archivo Excel
Estaciones_de_monitoreo = 'estaciones_monitoreo_colombia.xlsx'
# index=False evita que se cree una columna extra con los números de fila
estacion_monitoreo.to_excel(Estaciones_de_monitoreo, index=False)

# 2. Invocamos la descarga
files.download(Estaciones_de_monitoreo)

print("✅ Se descargo el dataframe Estaciones_de_monitoreo correctamente")

✅ Se descargo el dataframe Estaciones_de_monitoreo correctamente

La **octava tabla especializada** creada fue la tabla de **medicion calidad aire**, donde se recopila la **información de los valores de los contaminantes atmosfericos registrados por estacion**

**NOTA:** Se crearon *datos dummy* de los contaminantes atmosfericos.


| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero) |
| **id_estacion** | `object` (String) |
| **id_tiempo** | `int64` (Entero) |
| **pm25** | `float64` (Decimal) |
| **pm10** | `float64` (Decimal) |
| **no2** | `float64` (Decimal) |
| **so2** | `float64` (Decimal) |
| **co** | `float64` (Decimal) |
| **o3** | `float64` (Decimal) |
| **temperatura** | `float64` (Decimal) |
| **humedad** | `float64` (Decimal) |

In [ ]:
# ============================================================
# PASO 1: Definir rangos realistas de contaminantes
# Basados en datos típicos de ciudades colombianas según IDEAM
# Unidades: pm25 y pm10 (µg/m³), no2/so2/co/o3 (µg/m³)
# temperatura (°C), humedad (%)
# ============================================================
rangos = {
    # Contaminante: (min, max) según niveles típicos Colombia
    'pm25':        (5.0,   75.0),   # Bogotá/Medellín pueden superar 50 en temporadas
    'pm10':        (10.0,  150.0),  # Ciudades industriales pueden llegar a 150
    'no2':         (5.0,   80.0),   # Zonas urbanas con tráfico
    'so2':         (1.0,   30.0),   # Zonas industriales
    'co':          (0.1,   10.0),   # Monóxido de carbono
    'o3':          (10.0,  120.0),  # Ozono, más alto en horas pico
    'temperatura': (10.0,  35.0),   # Rango amplio por diversidad altitudinal
    'humedad':     (40.0,  95.0),   # Colombia tiene alta humedad en general
}

# ============================================================
# PASO 2: Generar múltiples mediciones por estación por mes
# Se generan entre 3 y 5 mediciones por estación/mes
# combinando con los id_tiempo de la tabla tiempo
# ============================================================
np.random.seed(42)  # Semilla para reproducibilidad

registros = []

for _, estacion in estacion_monitoreo.iterrows():
    for _, t in tiempo.iterrows():
        # Número aleatorio de mediciones por estación/mes (entre 3 y 5)
        n_mediciones = np.random.randint(3, 6)

        for _ in range(n_mediciones):
            registros.append({
                'id_estacion': estacion['id'],#FK
                'id_tiempo':   t['id'], #FK
                'pm25':        round(np.random.uniform(*rangos['pm25']),        2),
                'pm10':        round(np.random.uniform(*rangos['pm10']),        2),
                'no2':         round(np.random.uniform(*rangos['no2']),         2),
                'so2':         round(np.random.uniform(*rangos['so2']),         2),
                'co':          round(np.random.uniform(*rangos['co']),          2),
                'o3':          round(np.random.uniform(*rangos['o3']),          2),
                'temperatura': round(np.random.uniform(*rangos['temperatura']), 2),
                'humedad':     round(np.random.uniform(*rangos['humedad']),     2),
            })


# ============================================================
# PASO 3: Construir el dataframe medicion_calidad_aire
# El ID se genera como autoincremental desde 1
# ============================================================
medicion_calidad_aire = pd.DataFrame(registros)
medicion_calidad_aire.insert(0, 'id', range(1, len(medicion_calidad_aire) + 1))


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
print("Shape tabla medicion_calidad_aire:", medicion_calidad_aire.shape)
print("\nValores nulos por columna:")
print(medicion_calidad_aire.isnull().sum())
print("\nEstadísticas descriptivas:")
print(medicion_calidad_aire.describe().round(2))
print("\nPrimeras filas:")
medicion_calidad_aire.head()

Shape tabla medicion_calidad_aire: (11710, 11)

Valores nulos por columna:
id             0
id_estacion    0
id_tiempo      0
pm25           0
pm10           0
no2            0
so2            0
co             0
o3             0
temperatura    0
humedad        0
dtype: int64

Estadísticas descriptivas:
             id  id_estacion  id_tiempo      pm25      pm10       no2  \
count  11710.00     11710.00   11710.00  11710.00  11710.00  11710.00
mean    5855.50        30.98      24.44     40.37     79.37     42.84
std     3380.53        17.58      13.88     20.16     40.26     21.61
min        1.00         1.00       1.00      5.01     10.00      5.01
25%     2928.25        16.00      12.00     22.87     44.34     24.30
50%     5855.50        31.00      24.00     40.72     78.94     42.83
75%     8782.75        46.00      36.00     57.96    114.02     61.77
max    11710.00        61.00      48.00     74.99    149.99     79.99

            so2        co        o3  temperatura   humedad
count  11710.00  11710.00  11710.00     11710.00  11710.00
mean      15.54      5.04     65.26        22.54     67.35
std        8.38      2.86     31.59         7.28     15.93
min        1.00      0.10     10.01        10.00     40.01
25%        8.31      2.54     38.12        16.24     53.43
50%       15.54      5.01     65.48        22.55     67.32
75%       22.81      7.52     92.43        28.93     81.17
max       30.00     10.00    119.99        35.00     94.99

Primeras filas:

,id,id_estacion,id_tiempo,pm25,pm10,no2,so2,co,o3,temperatura,humedad
0,1,1,1,60.76,35.68,63.48,18.31,4.51,21.00,21.48,58.35
1,2,1,1,15.00,101.12,9.23,21.94,9.39,10.09,34.81,73.96
2,3,1,1,47.82,10.99,6.73,16.22,4.06,15.13,34.34,52.80
3,4,1,1,11.34,96.57,33.68,29.51,4.72,104.59,27.01,64.78
4,5,1,1,5.93,141.91,47.25,12.18,0.26,35.40,16.03,77.58

La **novena tabla especializada** creada fue la tabla de **indice calidad aire**, donde se recopila la **información con respecto al indice de calidad del aire segun los niveles de los contaminantes atmosfericos registrados por estacion**


| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero) |
| **id_medicion** | `int64` (Entero) |
| **id_estacion** | `int64` (Entero) |
| **id_tiempo** | `int64` (Entero) |
| **ica_pm25** | `float64` (Decimal) |
| **ica_pm10** | `float64` (Decimal) |
| **ica_no2** | `float64` (Decimal) |
| **ica_so2** | `float64` (Decimal) |
| **ica_co** | `float64` (Decimal) |
| **ica_o3** | `float64` (Decimal) |
| **ica_general** | `float64` (Decimal) |
| **nivel_riesgo** | `category` (Categórico)|

In [ ]:
# ============================================================
# Tabla: indice_calidad_aire
# Calcula el ICA por medición siguiendo el estándar IDEAM
# Resolución 2254 de 2017 - Ministerio de Ambiente Colombia
# ============================================================

# ============================================================
# PASO 1: Definir umbrales IDEAM para cada contaminante
# Basados en la Resolución 2254/2017 del MinAmbiente Colombia
# Formato: (limite_inferior, limite_superior, ica_inferior, ica_superior)
# ============================================================
umbrales = {
    'pm25': [
        (0.0,  12.0,   0,  50),   # Bueno
        (12.1, 37.0,  51, 100),   # Aceptable
        (37.1, 55.0, 101, 150),   # Dañino grupos sensibles
        (55.1, 150.0,151, 200),   # Dañino
        (150.1,250.0,201, 300),   # Muy dañino
        (250.1,500.0,301, 500),   # Peligroso
    ],
    'pm10': [
        (0.0,   54.0,  0,  50),
        (55.0,  154.0, 51, 100),
        (155.0, 254.0,101, 150),
        (255.0, 354.0,151, 200),
        (355.0, 424.0,201, 300),
        (425.0, 604.0,301, 500),
    ],
    'no2': [
        (0.0,   53.0,  0,  50),
        (54.0,  100.0, 51, 100),
        (101.0, 360.0,101, 150),
        (361.0, 649.0,151, 200),
        (650.0, 1249.0,201,300),
        (1250.0,2049.0,301,500),
    ],
    'so2': [
        (0.0,   35.0,  0,  50),
        (36.0,  75.0,  51, 100),
        (76.0,  185.0,101, 150),
        (186.0, 304.0,151, 200),
        (305.0, 604.0,201, 300),
        (605.0, 1004.0,301,500),
    ],
    'co': [
        (0.0,  4.4,   0,  50),
        (4.5,  9.4,  51, 100),
        (9.5,  12.4,101, 150),
        (12.5, 15.4,151, 200),
        (15.5, 30.4,201, 300),
        (30.5, 50.4,301, 500),
    ],
    'o3': [
        (0.0,   54.0,  0,  50),
        (55.0,  70.0,  51, 100),
        (71.0,  85.0, 101, 150),
        (86.0,  105.0,151, 200),
        (106.0, 200.0,201, 300),
        (201.0, 404.0,301, 500),
    ],
}

# ============================================================
# PASO 2: Función para calcular ICA por contaminante
# Usa interpolación lineal dentro del rango correspondiente
# ============================================================
def calcular_ica(valor, contaminante):
    if pd.isna(valor):
        return None
    for (c_low, c_high, i_low, i_high) in umbrales[contaminante]:
        if c_low <= valor <= c_high:
            # Fórmula interpolación lineal ICA
            ica = ((i_high - i_low) / (c_high - c_low)) * (valor - c_low) + i_low
            return round(ica, 2)
    return 500  # Si supera todos los rangos es peligroso

# ============================================================
# PASO 3: Función para asignar nivel de riesgo según ICA
# Basado en categorías IDEAM Resolución 2254/2017
# ============================================================
def nivel_riesgo(ica):
    if pd.isna(ica):
        return 'Sin dato'
    if ica <= 50:
        return 'Bueno'
    elif ica <= 100:
        return 'Aceptable'
    elif ica <= 150:
        return 'Dañino para grupos sensibles'
    elif ica <= 200:
        return 'Dañino'
    elif ica <= 300:
        return 'Muy dañino'
    else:
        return 'Peligroso'

# ============================================================
# PASO 4: Calcular ICA para cada medición
# El ICA general es el máximo entre todos los contaminantes
# ya que el peor contaminante define el nivel de riesgo
# ============================================================
ica_df = medicion_calidad_aire.copy()

# Calculamos ICA por cada contaminante
ica_df['ica_pm25'] = ica_df['pm25'].apply(lambda x: calcular_ica(x, 'pm25'))
ica_df['ica_pm10'] = ica_df['pm10'].apply(lambda x: calcular_ica(x, 'pm10'))
ica_df['ica_no2']  = ica_df['no2'].apply(lambda x: calcular_ica(x, 'no2'))
ica_df['ica_so2']  = ica_df['so2'].apply(lambda x: calcular_ica(x, 'so2'))
ica_df['ica_co']   = ica_df['co'].apply(lambda x: calcular_ica(x, 'co'))
ica_df['ica_o3']   = ica_df['o3'].apply(lambda x: calcular_ica(x, 'o3'))

# ICA general = máximo entre todos los contaminantes
ica_df['ica_general'] = ica_df[['ica_pm25','ica_pm10','ica_no2',
                                  'ica_so2','ica_co','ica_o3']].max(axis=1)

# Asignamos nivel de riesgo según ICA general
ica_df['nivel_riesgo'] = ica_df['ica_general'].apply(nivel_riesgo)


# ============================================================
# PASO 5: Construir la tabla indice_calidad_aire
# ============================================================
indice_calidad_aire = pd.DataFrame({
    'id':           range(1, len(ica_df) + 1),       # PK autoincremental
    'id_medicion':  ica_df['id'],                     # FK → medicion_calidad_aire
    'id_estacion':  ica_df['id_estacion'],            # FK → estacion_monitoreo
    'id_tiempo':    ica_df['id_tiempo'],              # FK → tiempo
    'ica_pm25':     ica_df['ica_pm25'],               # ICA calculado para PM2.5
    'ica_pm10':     ica_df['ica_pm10'],               # ICA calculado para PM10
    'ica_no2':      ica_df['ica_no2'],                # ICA calculado para NO2
    'ica_so2':      ica_df['ica_so2'],                # ICA calculado para SO2
    'ica_co':       ica_df['ica_co'],                 # ICA calculado para CO
    'ica_o3':       ica_df['ica_o3'],                 # ICA calculado para O3
    'ica_general':  ica_df['ica_general'],            # ICA general (máximo)
    'nivel_riesgo': ica_df['nivel_riesgo']            # Categoría IDEAM
})


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
print("Shape tabla indice_calidad_aire:", indice_calidad_aire.shape)
print("\nValores nulos por columna:")
print(indice_calidad_aire.isnull().sum())
print("\nDistribución por nivel de riesgo:")
print(indice_calidad_aire['nivel_riesgo'].value_counts())
print("\nPrimeras filas:")
indice_calidad_aire.head()

Shape tabla indice_calidad_aire: (11710, 12)

Valores nulos por columna:
id              0
id_medicion     0
id_estacion     0
id_tiempo       0
ica_pm25        0
ica_pm10        0
ica_no2         0
ica_so2         0
ica_co          0
ica_o3          0
ica_general     0
nivel_riesgo    0
dtype: int64

Distribución por nivel de riesgo:
nivel_riesgo
Dañino                          4133
Dañino para grupos sensibles    2683
Aceptable                       2524
Muy dañino                      1427
Peligroso                        910
Bueno                             33
Name: count, dtype: int64

Primeras filas:

,id,id_medicion,id_estacion,id_tiempo,ica_pm25,ica_pm10,ica_no2,ica_so2,ica_co,ica_o3,ica_general,nivel_riesgo
0,1,1,1,1,153.92,33.04,61.10,26.16,51.10,19.44,153.92,Dañino
1,2,2,1,1,56.71,73.83,8.71,31.34,99.90,9.34,99.90,Aceptable
2,3,3,1,1,130.35,10.18,6.35,23.17,46.14,14.01,130.35,Dañino para grupos sensibles
3,4,4,1,1,47.25,71.58,31.77,42.16,53.20,198.94,198.94,Dañino
4,5,5,1,1,24.71,94.02,44.58,17.40,2.95,32.78,94.02,Aceptable

La **decima tabla especializada** creada fue la tabla de **diagnostico_cie10**, donde se recopila la **información con respecto a la causa de defunción según los códigos CIE-10**


| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero) |
| **nombre** | `object` (String) |
| **categoria** | `object` (String) |
| **es_respiratorio** | `bool` (Booleano) |

In [ ]:
# ============================================================
# Tabla: diagnostico_cie10
# Catálogo de códigos CIE-10 relevantes para el análisis de
# mortalidad asociada a calidad del aire en Colombia 2024
# ============================================================

diagnosticos_data = [

    # -------------------------------------------------------
    # J00-J06: Infecciones agudas vías respiratorias superiores
    # -------------------------------------------------------
    {'id': 'J00',  'nombre': 'Rinofaringitis aguda (resfriado común)',                     'categoria': 'Infecciones agudas vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J01',  'nombre': 'Sinusitis aguda',                                             'categoria': 'Infecciones agudas vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J02',  'nombre': 'Faringitis aguda',                                            'categoria': 'Infecciones agudas vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J03',  'nombre': 'Amigdalitis aguda',                                           'categoria': 'Infecciones agudas vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J04',  'nombre': 'Laringitis y traqueítis agudas',                              'categoria': 'Infecciones agudas vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J05',  'nombre': 'Laringitis obstructiva aguda y epiglotitis',                  'categoria': 'Infecciones agudas vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J06',  'nombre': 'Infecciones agudas de vías respiratorias superiores múltiples','categoria': 'Infecciones agudas vías respiratorias superiores',   'es_respiratorio': True},

    # -------------------------------------------------------
    # J09-J18: Influenza y neumonía
    # -------------------------------------------------------
    {'id': 'J09',  'nombre': 'Influenza debida a virus de la gripe identificado',           'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J10',  'nombre': 'Influenza debida a otro virus de la gripe identificado',      'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J11',  'nombre': 'Influenza debida a virus no identificado',                    'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J12',  'nombre': 'Neumonía viral no clasificada en otra parte',                 'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J13',  'nombre': 'Neumonía debida a Streptococcus pneumoniae',                  'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J14',  'nombre': 'Neumonía debida a Haemophilus influenzae',                    'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J15',  'nombre': 'Neumonía bacteriana no clasificada en otra parte',            'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J16',  'nombre': 'Neumonía debida a otros microorganismos infecciosos',         'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J17',  'nombre': 'Neumonía en enfermedades clasificadas en otra parte',         'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J18',  'nombre': 'Neumonía organismo no especificado',                          'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},

    # -------------------------------------------------------
    # J20-J22: Infecciones agudas vías respiratorias inferiores
    # -------------------------------------------------------
    {'id': 'J20',  'nombre': 'Bronquitis aguda',                                            'categoria': 'Infecciones agudas vías respiratorias inferiores',   'es_respiratorio': True},
    {'id': 'J21',  'nombre': 'Bronquiolitis aguda',                                         'categoria': 'Infecciones agudas vías respiratorias inferiores',   'es_respiratorio': True},
    {'id': 'J22',  'nombre': 'Infección aguda no especificada de vías respiratorias inferiores','categoria': 'Infecciones agudas vías respiratorias inferiores','es_respiratorio': True},

    # -------------------------------------------------------
    # J30-J39: Otras enfermedades vías respiratorias superiores
    # -------------------------------------------------------
    {'id': 'J30',  'nombre': 'Rinitis alérgica y vasomotora',                               'categoria': 'Otras enfermedades vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J31',  'nombre': 'Rinitis, rinofaringitis y faringitis crónicas',               'categoria': 'Otras enfermedades vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J32',  'nombre': 'Sinusitis crónica',                                           'categoria': 'Otras enfermedades vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J33',  'nombre': 'Pólipo nasal',                                                'categoria': 'Otras enfermedades vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J35',  'nombre': 'Enfermedades crónicas de amígdalas y adenoides',              'categoria': 'Otras enfermedades vías respiratorias superiores',   'es_respiratorio': True},
    {'id': 'J38',  'nombre': 'Enfermedades de cuerdas vocales y laringe',                   'categoria': 'Otras enfermedades vías respiratorias superiores',   'es_respiratorio': True},

    # -------------------------------------------------------
    # J40-J47: Enfermedades crónicas vías respiratorias inferiores
    # Directamente asociadas a contaminación del aire
    # -------------------------------------------------------
    {'id': 'J40',  'nombre': 'Bronquitis no especificada como aguda o crónica',             'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J41',  'nombre': 'Bronquitis crónica simple y mucopurulenta',                   'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J42',  'nombre': 'Bronquitis crónica no especificada',                          'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J43',  'nombre': 'Enfisema pulmonar',                                           'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J44',  'nombre': 'Enfermedad pulmonar obstructiva crónica (EPOC)',              'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J45',  'nombre': 'Asma',                                                        'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J46',  'nombre': 'Estado asmático',                                             'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J47',  'nombre': 'Bronquiectasia',                                              'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},

    # -------------------------------------------------------
    # J60-J70: Enfermedades por agentes externos
    # Muy relevantes para contaminación del aire
    # -------------------------------------------------------
    {'id': 'J60',  'nombre': 'Neumoconiosis del minero del carbón',                         'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J61',  'nombre': 'Neumoconiosis debida al asbesto y otras fibras minerales',    'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J62',  'nombre': 'Neumoconiosis debida al polvo que contiene sílice',           'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J63',  'nombre': 'Neumoconiosis debida a otros polvos inorgánicos',             'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J64',  'nombre': 'Neumoconiosis no especificada',                               'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J65',  'nombre': 'Neumoconiosis asociada con tuberculosis',                     'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J66',  'nombre': 'Enfermedad de vías respiratorias debida a polvos orgánicos',  'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J67',  'nombre': 'Neumonitis por hipersensibilidad debida a polvos orgánicos',  'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J68',  'nombre': 'Afecciones respiratorias debidas a inhalación de gases',      'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J69',  'nombre': 'Neumonitis debida a sólidos y líquidos',                      'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},
    {'id': 'J70',  'nombre': 'Afecciones respiratorias debidas a otros agentes externos',   'categoria': 'Enfermedades por agentes externos',                  'es_respiratorio': True},

    # -------------------------------------------------------
    # J80-J99: Otras enfermedades respiratorias
    # -------------------------------------------------------
    {'id': 'J80',  'nombre': 'Síndrome de dificultad respiratoria del adulto',              'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},
    {'id': 'J81',  'nombre': 'Edema pulmonar',                                              'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},
    {'id': 'J82',  'nombre': 'Eosinofilia pulmonar no clasificada en otra parte',           'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},
    {'id': 'J84',  'nombre': 'Otras enfermedades pulmonares intersticiales',                'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},
    {'id': 'J85',  'nombre': 'Absceso del pulmón y del mediastino',                        'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},
    {'id': 'J86',  'nombre': 'Piotórax',                                                    'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},
    {'id': 'J90',  'nombre': 'Derrame pleural no clasificado en otra parte',                'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},
    {'id': 'J96',  'nombre': 'Insuficiencia respiratoria no clasificada en otra parte',     'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},
    {'id': 'J98',  'nombre': 'Otros trastornos respiratorios',                              'categoria': 'Otras enfermedades respiratorias',                   'es_respiratorio': True},

    # -------------------------------------------------------
    # I00-I99: Enfermedades cardiovasculares
    # Evidencia científica las vincula a contaminación del aire
    # -------------------------------------------------------
    {'id': 'I10',  'nombre': 'Hipertensión esencial primaria',                              'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I11',  'nombre': 'Enfermedad cardíaca hipertensiva',                            'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I20',  'nombre': 'Angina de pecho',                                             'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I21',  'nombre': 'Infarto agudo de miocardio',                                  'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I22',  'nombre': 'Infarto de miocardio recurrente',                             'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I25',  'nombre': 'Enfermedad isquémica crónica del corazón',                   'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I26',  'nombre': 'Embolia pulmonar',                                            'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I27',  'nombre': 'Otras enfermedades cardiopulmonares',                         'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I50',  'nombre': 'Insuficiencia cardíaca',                                      'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I60',  'nombre': 'Hemorragia subaracnoidea',                                    'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I61',  'nombre': 'Hemorragia intracerebral',                                    'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I63',  'nombre': 'Infarto cerebral',                                            'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I64',  'nombre': 'Accidente vascular encefálico (ACV)',                         'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},

    # -------------------------------------------------------
    # C00-C97: Cánceres asociados a contaminación del aire
    # -------------------------------------------------------
    {'id': 'C33',  'nombre': 'Tumor maligno de tráquea',                                    'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C34',  'nombre': 'Tumor maligno de bronquios y pulmón',                         'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C45',  'nombre': 'Mesotelioma (asociado a asbesto)',                             'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},

    # -------------------------------------------------------
    # P00-P28: Afecciones perinatales respiratorias
    # -------------------------------------------------------
    {'id': 'P22',  'nombre': 'Dificultad respiratoria del recién nacido',                   'categoria': 'Afecciones perinatales respiratorias',               'es_respiratorio': True},
    {'id': 'P23',  'nombre': 'Neumonía congénita',                                          'categoria': 'Afecciones perinatales respiratorias',               'es_respiratorio': True},
    {'id': 'P24',  'nombre': 'Síndromes de aspiración neonatal',                            'categoria': 'Afecciones perinatales respiratorias',               'es_respiratorio': True},
    {'id': 'P25',  'nombre': 'Enfisema intersticial y afecciones relacionadas',             'categoria': 'Afecciones perinatales respiratorias',               'es_respiratorio': True},
    {'id': 'P28',  'nombre': 'Otros problemas respiratorios del recién nacido',             'categoria': 'Afecciones perinatales respiratorias',               'es_respiratorio': True},
]


# ============================================================
# Construir el dataframe diagnostico_cie10
# ============================================================
diagnostico_cie10 = pd.DataFrame(diagnosticos_data)


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
print("Shape tabla diagnostico_cie10:", diagnostico_cie10.shape)
print("\nValores nulos por columna:")
print(diagnostico_cie10.isnull().sum())
print("\nDistribución por categoría:")
print(diagnostico_cie10['categoria'].value_counts())
print("\nRespiratorios vs No respiratorios:")
print(diagnostico_cie10['es_respiratorio'].value_counts())
print("\nPrimeras filas:")
diagnostico_cie10.head()

Shape tabla diagnostico_cie10: (75, 4)

Valores nulos por columna:
id                 0
nombre             0
categoria          0
es_respiratorio    0
dtype: int64

Distribución por categoría:
categoria
Enfermedades cardiovasculares                          13
Enfermedades por agentes externos                      11
Influenza y neumonía                                   10
Otras enfermedades respiratorias                        9
Enfermedades crónicas vías respiratorias inferiores     8
Infecciones agudas vías respiratorias superiores        7
Otras enfermedades vías respiratorias superiores        6
Afecciones perinatales respiratorias                    5
Infecciones agudas vías respiratorias inferiores        3
Cánceres asociados a contaminación del aire             3
Name: count, dtype: int64

Respiratorios vs No respiratorios:
es_respiratorio
True     59
False    16
Name: count, dtype: int64

Primeras filas:

,id,nombre,categoria,es_respiratorio
0,J00,Rinofaringitis aguda (resfriado común),Infecciones agudas vías respiratorias superiores,True
1,J01,Sinusitis aguda,Infecciones agudas vías respiratorias superiores,True
2,J02,Faringitis aguda,Infecciones agudas vías respiratorias superiores,True
3,J03,Amigdalitis aguda,Infecciones agudas vías respiratorias superiores,True
4,J04,Laringitis y traqueítis agudas,Infecciones agudas vías respiratorias superiores,True

La **onceava tabla especializada** creada fue la tabla de **defuncion_diagnostico**, donde se recopila la **información con respecto a la enfermedad de defunción de la persona.**

**NOTA:** Esta es una tabla puente que conecta cada defunción con sus diagnósticos CIE-10 (causa básica y causas secundarias). Permite analizar comorbilidades en los fallecidos. Solo se incluyen los registros de causa básica (`C_BAS1`) del DANE.

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero autoincremental) |
| **id_defuncion** | `int64` (Entero) |
| **id_diagnostico** | `object` (String / Código CIE-10) |
| **es_causa_basica** | `bool` (Booleano) |

In [ ]:
# ============================================================
# Tabla: defuncion_diagnostico
# Tabla puente que conecta cada defunción con todos sus
# diagnósticos CIE-10 (causa básica + causas secundarias)
# Permite analizar comorbilidades en los fallecidos
# ============================================================

# ============================================================
# PASO 1: Definir las columnas de causas del dataset DANE
# C_BAS1    = Causa básica de muerte (principal)
# C_MUERTEB hasta C_MUERTEG = Causas secundarias (comorbilidades)
# ============================================================
# Se ajusta el diccionario para incluir solo las columnas que no fueron eliminadas previamente
columnas_causas = {
    'C_BAS1':    True,   # True = es causa básica
    # Las siguientes columnas fueron eliminadas en la limpieza de datos previa,
    # por lo que se comentan o eliminan para evitar el KeyError.
    # 'C_MUERTEB': False,  # False = es causa secundaria
    # 'C_MUERTEC': False,
    # 'C_MUERTED': False,
    # 'C_MUERTEE': False,
    # 'C_MUERTEF': False,
    # 'C_MUERTEG': False,
}

# ============================================================
# PASO 2: Ampliar el catálogo diagnostico_cie10
# El DANE usa códigos de 4 caracteres (ej. J440, J449)
# Agregamos los subcódigos más frecuentes del dataset
# ============================================================
nuevos_diagnosticos = [
    # Cardiovasculares
    {'id': 'I219', 'nombre': 'Infarto agudo de miocardio no especificado',                       'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I110', 'nombre': 'Enfermedad cardíaca hipertensiva con insuficiencia cardíaca',      'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I120', 'nombre': 'Enfermedad renal hipertensiva con insuficiencia renal',            'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I251', 'nombre': 'Enfermedad aterosclerótica del corazón',                           'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I259', 'nombre': 'Enfermedad isquémica crónica del corazón no especificada',        'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I249', 'nombre': 'Enfermedad isquémica aguda del corazón no especificada',          'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I489', 'nombre': 'Fibrilación y flutter auricular no especificado',                  'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I609', 'nombre': 'Hemorragia subaracnoidea no especificada',                        'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I619', 'nombre': 'Hemorragia intracerebral no especificada',                        'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I639', 'nombre': 'Infarto cerebral no especificado',                                 'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I694', 'nombre': 'Secuelas de accidente vascular encefálico',                       'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I693', 'nombre': 'Secuelas de infarto cerebral',                                    'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},
    {'id': 'I698', 'nombre': 'Secuelas de otras enfermedades cerebrovasculares',                 'categoria': 'Enfermedades cardiovasculares',                      'es_respiratorio': False},

    # Respiratorias
    {'id': 'J440', 'nombre': 'EPOC con infección respiratoria aguda',                            'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J441', 'nombre': 'EPOC con exacerbación aguda no especificada',                      'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J449', 'nombre': 'EPOC no especificada',                                             'categoria': 'Enfermedades crónicas vías respiratorias inferiores', 'es_respiratorio': True},
    {'id': 'J189', 'nombre': 'Neumonía no especificada',                                         'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J180', 'nombre': 'Bronconeumonía no especificada',                                   'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},
    {'id': 'J159', 'nombre': 'Neumonía bacteriana no especificada',                              'categoria': 'Influenza y neumonía',                               'es_respiratorio': True},

    # Cánceres
    {'id': 'C169', 'nombre': 'Tumor maligno del estómago no especificado',                       'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C189', 'nombre': 'Tumor maligno del colon no especificado',                          'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C20',  'nombre': 'Tumor maligno del recto',                                          'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C229', 'nombre': 'Tumor maligno del hígado no especificado',                         'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C259', 'nombre': 'Tumor maligno del páncreas no especificado',                       'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C349', 'nombre': 'Tumor maligno de bronquios y pulmón no especificado',              'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C509', 'nombre': 'Tumor maligno de mama no especificado',                            'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C539', 'nombre': 'Tumor maligno del cuello uterino no especificado',                 'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C56',  'nombre': 'Tumor maligno del ovario',                                         'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},
    {'id': 'C61',  'nombre': 'Tumor maligno de la próstata',                                     'categoria': 'Cánceres asociados a contaminación del aire',        'es_respiratorio': False},

    # Otras causas relevantes
    {'id': 'N189', 'nombre': 'Enfermedad renal crónica no especificada',                         'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'N390', 'nombre': 'Infección de vías urinarias no especificada',                      'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'E116', 'nombre': 'Diabetes mellitus tipo 2 con otras complicaciones',                'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'E117', 'nombre': 'Diabetes mellitus tipo 2 con complicaciones múltiples',            'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'E146', 'nombre': 'Diabetes mellitus no especificada con otras complicaciones',       'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'G301', 'nombre': 'Enfermedad de Alzheimer de inicio tardío',                         'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'G309', 'nombre': 'Enfermedad de Alzheimer no especificada',                          'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'F03',  'nombre': 'Demencia no especificada',                                         'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'K566', 'nombre': 'Obstrucción intestinal no especificada',                           'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'K746', 'nombre': 'Cirrosis hepática no especificada',                                'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'K922', 'nombre': 'Hemorragia gastrointestinal no especificada',                      'categoria': 'Otras enfermedades relevantes',                      'es_respiratorio': False},
    {'id': 'R98',  'nombre': 'Muerte sin asistencia',                                            'categoria': 'Causas externas y signos inespecíficos',             'es_respiratorio': False},
    {'id': 'R99',  'nombre': 'Otras causas mal definidas y las no especificadas',                'categoria': 'Causas externas y signos inespecíficos',             'es_respiratorio': False},
    {'id': 'A162', 'nombre': 'Tuberculosis pulmonar sin confirmación bacteriológica',            'categoria': 'Infecciones agudas vías respiratorias superiores',   'es_respiratorio': True},

    # Causas externas
    {'id': 'X954', 'nombre': 'Disparo de arma de fuego - calle o carretera',                    'categoria': 'Causas externas',                                    'es_respiratorio': False},
    {'id': 'X959', 'nombre': 'Disparo de arma de fuego - lugar no especificado',                'categoria': 'Causas externas',                                    'es_respiratorio': False},
    {'id': 'X958', 'nombre': 'Disparo de arma de fuego - otro lugar especificado',              'categoria': 'Causas externas',                                    'es_respiratorio': False},
    {'id': 'X700', 'nombre': 'Lesión autoinfligida - vivienda',                                 'categoria': 'Causas externas',                                    'es_respiratorio': False},
    {'id': 'V294', 'nombre': 'Motociclista lesionado en accidente de tránsito',                 'categoria': 'Causas externas',                                    'es_respiratorio': False},
]

# Agregamos los nuevos diagnósticos al catálogo existente
diagnostico_cie10 = pd.concat(
    [diagnostico_cie10, pd.DataFrame(nuevos_diagnosticos)],
    ignore_index=True
)


# ============================================================
# PASO 3: Transformar dataset de formato ancho a largo
# Cada fila tendrá: id_defuncion, codigo_cie10, es_causa_basica
# Se filtran valores inválidos que el DANE usa para celdas vacías
# ============================================================
valores_invalidos = {'1.0', '1', 'nan', 'NaN', '', 'None', '0', '0.0'}

registros = []
# Se itera solo sobre las columnas que realmente existen en df
for _, fila in df[['ID'] + list(columnas_causas.keys())].iterrows():
    for columna, es_basica in columnas_causas.items():
        codigo = str(fila[columna]).strip() if pd.notna(fila[columna]) else None
        if codigo and codigo not in valores_invalidos:
            registros.append({
                'id_defuncion':    fila['ID'],
                'id_diagnostico':  codigo,
                'es_causa_basica': es_basica
            })


# ============================================================
# PASO 4: Construir el dataframe defuncion_diagnostico
# ============================================================
defuncion_diagnostico = pd.DataFrame(registros)
defuncion_diagnostico.insert(0, 'id', range(1, len(defuncion_diagnostico) + 1))


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
codigos_catalogo  = diagnostico_cie10['id'].tolist()
en_catalogo       = defuncion_diagnostico['id_diagnostico'].isin(codigos_catalogo).sum()
total             = len(defuncion_diagnostico)

print("Shape catálogo diagnostico_cie10:", diagnostico_cie10.shape)
print("Shape tabla defuncion_diagnostico:", defuncion_diagnostico.shape)
print("\nValores nulos por columna:")
print(defuncion_diagnostico.isnull().sum())
print("\nCausas básicas vs secundarias:")
print(defuncion_diagnostico['es_causa_basica'].value_counts())
print(f"\nCobertura del catálogo: {en_catalogo:,} / {total:,} ({en_catalogo/total*100:.1f}%)")
print("\nTop 10 diagnósticos más frecuentes:")
print(defuncion_diagnostico['id_diagnostico'].value_counts().head(10))
print("\nPrimeras filas:")
defuncion_diagnostico.head(10)

Shape catálogo diagnostico_cie10: (123, 4)
Shape tabla defuncion_diagnostico: (240327, 4)

Valores nulos por columna:
id                 0
id_defuncion       0
id_diagnostico     0
es_causa_basica    0
dtype: int64

Causas básicas vs secundarias:
es_causa_basica
True    240327
Name: count, dtype: int64

Cobertura del catálogo: 142,305 / 240,327 (59.2%)

Top 10 diagnósticos más frecuentes:
id_diagnostico
I219    41725
J440     8052
J449     5751
C349     4703
C169     4703
J189     4327
C509     3882
C61      3627
N390     3516
I110     2997
Name: count, dtype: int64

Primeras filas:

   id  id_defuncion id_diagnostico  es_causa_basica
0   1        411195           I219             True
1   2        618864           C833             True
2   3        740610           I639             True
3   4       1586788           G909             True
4   5       1981119           G938             True
5   6       7846882           G938             True
6   7       2199906           I832             True
7   8       1716762           I850             True
8   9       8092821           I251             True
9  10       6656648           J441             True

La **doceava tabla especializada** creada fue la tabla de **municipio**, donde se recopila la **información con respecto al municipio de defunción de la persona.**

**NOTA:** La tabla municipio integra datos del Geoportal DIVIPOLA del DANE con proyecciones poblacionales 2024. Se incluyen 1.104 municipios con cabecera municipal registrada. La altitud no se incluye por no estar disponible en las fuentes oficiales.

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `object` (String / Código DIVIPOLA 5 dígitos) |
| **id_departamento** | `object` (String / Código DIVIPOLA 2 dígitos) |
| **nombre** | `object` (String) |
| **poblacion** | `int64` (Entero) |
| **latitud** | `float64` (Decimal / Flotante) |
| **longitud** | `float64` (Decimal / Flotante) |

In [ ]:
# ============================================================
# PASO 1: Cargar el archivo Geoportal DIVIPOLA
# header=1 porque los encabezados reales están en la fila 2 del Excel
# ============================================================
ruta_geo = '/content/drive/MyDrive/Datos DANE Mortalidad 2024/Geoportal del DANE - Codificación Divipola.xlsx'

geo = pd.read_excel(ruta_geo, header=1)

print('Columnas Geoportal:', geo.columns.tolist())
print('Shape Geoportal:', geo.shape)


# ============================================================
# PASO 2: Filtrar solo CABECERA MUNICIPAL
# ============================================================
geo_municipios = geo[geo['Tipo Centro Poblado'] == 'CABECERA MUNICIPAL'].copy()

print('\nMunicipios únicos tras filtro:', geo_municipios.shape[0])


# ============================================================
# PASO 3: Cargar proyecciones poblacionales 2024
# ============================================================
ruta_pob = '/content/drive/MyDrive/Datos DANE Mortalidad 2024/Proyecciones poblacionales 2024.xlsx'

proyecciones = pd.read_excel(
    ruta_pob,
    usecols=['COD_DPTO', 'COD_MUNIC', 'ÁREA GEOGRÁFICA', 'Total']
)
proyecciones = proyecciones[proyecciones['ÁREA GEOGRÁFICA'] == 'Total'].copy()

print('Shape proyecciones filtradas:', proyecciones.shape)


# ============================================================
# PASO 4: Estandarizar códigos para el join
# ============================================================
geo_municipios['Código Municipio']    = geo_municipios['Código Municipio'].astype(str).str.strip().str.zfill(5)
geo_municipios['Código Departamento'] = geo_municipios['Código Departamento'].astype(str).str.strip().str.zfill(2)
proyecciones['COD_MUNIC']             = proyecciones['COD_MUNIC'].astype(str).str.strip().str.zfill(5)
proyecciones['COD_DPTO']              = proyecciones['COD_DPTO'].astype(str).str.strip().str.zfill(2)


# ============================================================
# PASO 5: Join entre Geoportal y Proyecciones
# ============================================================
municipio_raw = geo_municipios.merge(
    proyecciones[['COD_DPTO', 'COD_MUNIC', 'Total']],
    left_on=['Código Departamento', 'Código Municipio'],
    right_on=['COD_DPTO', 'COD_MUNIC'],
    how='left'
)

print('\nMunicipios sin población:', municipio_raw['Total'].isnull().sum())


# ============================================================
# PASO 6: Construir la tabla 'municipio'
# Se excluye altitud por no estar disponible en las fuentes
# ============================================================
municipio = pd.DataFrame({
    'id':              municipio_raw['Código Municipio'],
    'id_departamento': municipio_raw['Código Departamento'],
    'nombre':          municipio_raw['Nombre Municipio'],
    'poblacion':       municipio_raw['Total'],
    'latitud':         municipio_raw['Latitud'],
    'longitud':        municipio_raw['Longitud']
}).reset_index(drop=True)


# ============================================================
# VERIFICACIÓN FINAL
# ============================================================
print('\nShape tabla municipio:', municipio.shape)
print('\nValores nulos por columna:')
print(municipio.isnull().sum())
print('\nPrimeras filas:')
municipio.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Datos DANE Mortalidad 2024/Geoportal del DANE - Codificación Divipola.xlsx'

**Resumen de tablas creadas:**

| # | Dataframe | Filas | Columnas | Tipo de datos |
| :---: | :--- | :---: | :---: | :--- |
| 1 | **persona** | 275.778 | 9 | Real |
| 2 | **tiempo** | 48 | 3 | Real |
| 3 | **defuncion** | 275.778 | 11 | Real |
| 4 | **causa_defuncion** | 275.778 | 4 | Real |
| 5 | **municipio** | 1.104 | 6 | Real |
| 6 | **departamento** | 33 | 3 | Real |
| 7 | **pais** | 73 | 2 | Real |
| 8 | **estacion_monitoreo** | 61 | 7 | Dummy |
| 9 | **medicion_calidad_aire** | 11.710 | 11 | Dummy |
| 10 | **indice_calidad_aire** | 11.710 | 12 | Calculado |
| 11 | **diagnostico_cie10** | 123 | 4 | Manual |
| 12 | **defuncion_diagnostico** | 275.778 | 4 | Real |
| 13 | **tasa_mortalidad** | 4.620 | 9 | Calculado |

**Total registros:** 1.132.594

In [ ]:
# ============================================================
# Resumen detallado de todos los dataframes creados
# Muestra filas, columnas y el listado de columnas de cada uno
# ============================================================

dataframes = {
    'persona':         persona,
    'tiempo':          tiempo,
    'defuncion':       defuncion,
    'causa_defuncion': causa_defuncion,
    'municipio':       municipio,
    'departamento':    departamento,
    'pais':            pais,
    'estacion_monitoreo': estacion_monitoreo,
    'medicion_calidad_aire': medicion_calidad_aire,
    'diagnostico_cie10': diagnostico_cie10,
    'indice_calidad_aire': indice_calidad_aire,
    'defuncion_diagnostico': defuncion_diagnostico
}

for nombre, df_temp in dataframes.items():
    print("=" * 55)
    print(f"  📋 {nombre.upper()}")
    print(f"     Filas: {df_temp.shape[0]:,}  |  Columnas: {df_temp.shape[1]}")
    print("-" * 55)
    for col in df_temp.columns:
        print(f"     • {col}")
print("=" * 55)

### **D) Crear dataframe de "Tasa de mortalidad"**

Para realizar la correlación entre los valores del **índice de calidad del aire y la tasa de mortalidad por enfermedades respiratorias en Colombia** por departamento, se construyó la tabla **tasa_mortalidad**, que calcula 4 indicadores epidemiológicos estándar OPS/OMS por municipio y departamento.

La **decimotercera tabla especializada** creada fue la tabla de **tasa_mortalidad**, donde se calculan las **tasas epidemiológicas de mortalidad por municipio y departamento para Colombia 2024.**

**Indicadores calculados:**

| Indicador | Descripción | Fórmula |
| :--- | :--- | :--- |
| **TMG** | Tasa de Mortalidad General | (Muertes totales / Población) × 100.000 |
| **TMCE** | Tasa de Mortalidad por Causa Específica | (Muertes respiratorias / Población) × 100.000 |
| **TMAE** | Tasa de Mortalidad Ajustada por Edad | Suma ponderada por grupos quinquenales (estándar OPS 2000) |
| **AVPP** | Años de Vida Potencialmente Perdidos | Suma(70 - edad_muerte) para fallecidos menores de 70 años |

**NOTA:** La tabla se organiza en **formato largo** (una fila por tasa, geografía y período), cubriendo 1.123 municipios y 33 departamentos de Colombia.

| Variables | Tipo de Dato |
| :--- | :--- |
| **id** | `int64` (Entero autoincremental) |
| **id_tiempo** | `int64` (Entero - FK tabla tiempo) |
| **nivel_geografico** | `object` (String: 'municipio' o 'departamento') |
| **id_geografia** | `object` (String / Código DIVIPOLA) |
| **tipo_tasa** | `object` (String: TMG, TMCE, TMAE o AVPP) |
| **causa** | `object` (String: 'TODAS' o 'RESPIRATORIA') |
| **valor** | `float64` (Decimal) |
| **poblacion_base** | `int64` (Entero - Proyección 2024) |
| **total_muertes** | `int64` (Entero) |

Para realizar la correlacion entre los valores del indice de calidad de aire y la tasa de mortalidad por enfermedades respiratorias en Colombia por departamento, necesitamos este ultimo valor, ya que es el mas esencial para nuestro analisis.

In [ ]:
ruta_pob = '/content/drive/MyDrive/Datos DANE Mortalidad 2024/Proyecciones poblacionales 2024.xlsx'

# Cargar librerias
import pandas as pd
import numpy as np

# ============================================================
# 1. Preparar datos de Municipio
# ============================================================
info_municipios = municipio[['id', 'id_departamento', 'poblacion']].copy()
info_municipios.rename(columns={'id': 'id_municipio', 'poblacion': 'poblacion_municipio'}, inplace=True)

# ============================================================
# 2. Preparar datos de Departamento (Población Dummy)
# ============================================================
lista_departamentos = departamento[['id']].drop_duplicates().copy()
lista_departamentos.rename(columns={'id': 'id_departamento'}, inplace=True)

np.random.seed(42)
lista_departamentos['poblacion_departamento'] = np.random.randint(300000, 4000000, size=len(lista_departamentos))

# ============================================================
# 3. Calcular Defunciones (Muertes)
# ============================================================
# Ajuste a 6 dígitos: COD_DPTO (2) + '5' + COD_MUNIC (3) para coincidir con la tabla municipio
df_temp = df.copy()
df_temp['id_municipio'] = (
    df_temp['COD_DPTO'].astype(str).str.zfill(2) +
    "5" +
    df_temp['COD_MUNIC'].astype(str).str.zfill(3)
)

muertes_por_municipio = df_temp.groupby('id_municipio').size().reset_index(name='total_defunciones')

# Agrupamos por departamento
muertes_por_departamento = df_temp.groupby('COD_DPTO').size().reset_index(name='total_defunciones_dept')
muertes_por_departamento['COD_DPTO'] = muertes_por_departamento['COD_DPTO'].astype(str).str.zfill(2)

# ============================================================
# 4. Construir Tabla Tasa de Mortalidad
# ============================================================
tasa_mortalidad = pd.merge(muertes_por_municipio,
                           info_municipios,
                           on='id_municipio',
                           how='left')

# Calcular tasa municipal (por 100k y en porcentaje)
tasa_mortalidad['tm_municipio'] = (tasa_mortalidad['total_defunciones'] / tasa_mortalidad['poblacion_municipio']) * 100000
tasa_mortalidad['tm_municipio_porcentaje'] = (tasa_mortalidad['total_defunciones'] / tasa_mortalidad['poblacion_municipio']) * 100

# Unir con departamentos
tasa_mortalidad = pd.merge(tasa_mortalidad,
                           lista_departamentos,
                           on='id_departamento',
                           how='left')

tasa_mortalidad = pd.merge(tasa_mortalidad,
                           muertes_por_departamento,
                           left_on='id_departamento',
                           right_on='COD_DPTO',
                           how='left')

# Calcular tasa departamental (por 100k y en porcentaje)
tasa_mortalidad['tm_departamento'] = (tasa_mortalidad['total_defunciones_dept'] / tasa_mortalidad['poblacion_departamento']) * 100000
tasa_mortalidad['tm_departamento_porcentaje'] = (tasa_mortalidad['total_defunciones_dept'] / tasa_mortalidad['poblacion_departamento']) * 100

# ============================================================
# 5. Limpieza Final
# ============================================================
tasa_mortalidad.insert(0, 'id', range(1, len(tasa_mortalidad) + 1))
tasa_mortalidad_final = tasa_mortalidad[['id', 'id_departamento', 'id_municipio', 'tm_municipio', 'tm_municipio_porcentaje', 'tm_departamento', 'tm_departamento_porcentaje']].copy()

# Redondeo
tasa_mortalidad_final[['tm_municipio', 'tm_departamento']] = tasa_mortalidad_final[['tm_municipio', 'tm_departamento']].round(2)
tasa_mortalidad_final[['tm_municipio_porcentaje', 'tm_departamento_porcentaje']] = tasa_mortalidad_final[['tm_municipio_porcentaje', 'tm_departamento_porcentaje']].round(4)

print("✅ Tabla 'tasa_mortalidad' actualizada con porcentajes.")
display(tasa_mortalidad_final.dropna(subset=['id_departamento']).head())
print(f"")

In [ ]:
# Calcular el promedio de la tasa de mortalidad por departamento
promedio_mortalidad_depto = tasa_mortalidad_final.groupby('id_departamento')['tm_departamento'].mean().reset_index()

# Renombrar columna para mayor claridad
promedio_mortalidad_depto.columns = ['id_departamento', 'promedio_tm_departamento']

# Mostrar resultados ordenados de mayor a menor tasa
display(promedio_mortalidad_depto.sort_values(by='promedio_tm_departamento', ascending=False))

## **1.2.1. Modelo Relacional**

A continuación se describe el **modelo relacional** que estructura la base de datos del proyecto, indicando las llaves primarias (PK), llaves foráneas (FK) y las relaciones entre las 13 tablas.

### **Entidades principales**

| Tabla | PK | Descripción |
| :--- | :--- | :--- |
| **persona** | `id` | Información sociodemográfica del fallecido |
| **defuncion** | `id` | Registro central de cada defunción |
| **causa_defuncion** | `id` | Causa básica CIE-10 y lista OPS 667 por defunción |
| **defuncion_diagnostico** | `id` | Tabla puente: defunción ↔ diagnósticos CIE-10 |
| **diagnostico_cie10** | `id` | Catálogo de códigos CIE-10 con categoría y tipo |
| **tiempo** | `id` | Dimensión temporal (año y mes) |
| **municipio** | `id` | Municipios con población, latitud y longitud |
| **departamento** | `id` | Departamentos con región geográfica |
| **pais** | `id` | Países de nacimiento (estándar M49 ONU) |
| **estacion_monitoreo** | `id` | Estaciones de calidad del aire por municipio |
| **medicion_calidad_aire** | `id` | Mediciones de contaminantes por estación y período |
| **indice_calidad_aire** | `id` | ICA calculado por medición (Res. 2254/2017 IDEAM) |
| **tasa_mortalidad** | `id` | Tasas epidemiológicas por municipio y departamento |

### **Relaciones entre tablas (FK)**

| Tabla origen | Columna FK | Tabla destino | Columna PK | Cardinalidad |
| :--- | :--- | :--- | :--- | :--- |
| **defuncion** | `id_persona` | persona | `id` | 1 : 1 |
| **defuncion** | `id_tiempo` | tiempo | `id` | N : 1 |
| **defuncion** | `id_municipio_ocurrencia` | municipio | `id` | N : 1 |
| **defuncion** | `id_municipio_residencia` | municipio | `id` | N : 1 |
| **causa_defuncion** | `id_defuncion` | defuncion | `id` | 1 : 1 |
| **defuncion_diagnostico** | `id_defuncion` | defuncion | `id` | N : 1 |
| **defuncion_diagnostico** | `id_diagnostico` | diagnostico_cie10 | `id` | N : 1 |
| **persona** | `id_pais_nacimiento` | pais | `id` | N : 1 |
| **municipio** | `id_departamento` | departamento | `id` | N : 1 |
| **estacion_monitoreo** | `id_municipio` | municipio | `id` | N : 1 |
| **medicion_calidad_aire** | `id_estacion` | estacion_monitoreo | `id` | N : 1 |
| **medicion_calidad_aire** | `id_tiempo` | tiempo | `id` | N : 1 |
| **indice_calidad_aire** | `id_medicion` | medicion_calidad_aire | `id` | 1 : 1 |
| **indice_calidad_aire** | `id_estacion` | estacion_monitoreo | `id` | N : 1 |
| **indice_calidad_aire** | `id_tiempo` | tiempo | `id` | N : 1 |
| **tasa_mortalidad** | `id_tiempo` | tiempo | `id` | N : 1 |

> **Nota:** Las columnas `id_geografia` de `tasa_mortalidad` referencian a `municipio.id` o `departamento.id` según el valor de `nivel_geografico` ('municipio' / 'departamento').

## **1.2.2. Resultados del proceso ETL**

A continuación se presentan los resultados consolidados del proceso de **Extracción, Transformación y Carga (ETL)**, incluyendo las métricas de calidad de cada tabla generada.

### **A) Tabla integral (dataset DANE original)**

| Métrica | Valor |
| :--- | :--- |
| Registros originales | 275.778 |
| Variables originales | 61 |
| Fuente | DANE – Defunciones no fetales 2024 |
| Codificación | Latin-1 |
| Separador | Coma (`,`) |

### **B) Reducción por limpieza y filtrado**

| Paso | Acción | Resultado |
| :--- | :--- | :--- |
| Creación de ID único | IDs aleatorios en rango 10.000 – 9.999.999 | 275.778 IDs únicos ✅ |
| Eliminación por nulos | 29 columnas con alta tasa de nulos eliminadas | 32 columnas restantes |
| Eliminación por irrelevancia | 9 columnas redundantes o no útiles eliminadas | 23 columnas restantes |
| Filtro P_PMAN_IRIS | Solo defunciones de causa natural (código = 0) | Registros conservados: 275.778 |

### **C) Métricas de calidad por tabla**

| Tabla | Filas | Columnas | Nulos críticos | Tipo |
| :--- | ---: | :---: | :--- | :--- |
| **persona** | 275.778 | 9 | `area_residencia`: 4.568 | Real |
| **tiempo** | 48 | 3 | Ninguno ✅ | Real |
| **defuncion** | 275.778 | 11 | `probable_manera_muerte`: 6.001 · `ocupacion_causa_muerte`: 275.677 | Real |
| **causa_defuncion** | 275.778 | 4 | Ninguno ✅ | Real |
| **municipio** | 1.104 | 6 | Ninguno ✅ | Real |
| **departamento** | 33 | 3 | Ninguno ✅ | Real |
| **pais** | 73 | 2 | Ninguno ✅ | Real |
| **estacion_monitoreo** | 61 | 7 | Ninguno ✅ | Dummy |
| **medicion_calidad_aire** | 11.710 | 11 | Ninguno ✅ | Dummy |
| **indice_calidad_aire** | 11.710 | 12 | Ninguno ✅ | Calculado |
| **diagnostico_cie10** | 123 | 4 | Ninguno ✅ | Manual |
| **defuncion_diagnostico** | 275.778 | 4 | Ninguno ✅ | Real |
| **tasa_mortalidad** | 4.620 | 9 | Ninguno ✅ | Calculado |

### **D) Distribución del ICA por nivel de riesgo**

| Nivel de riesgo | Registros | % del total |
| :--- | ---: | ---: |
| Dañino | 4.133 | 35,3% |
| Dañino para grupos sensibles | 2.683 | 22,9% |
| Aceptable | 2.524 | 21,6% |
| Muy dañino | 1.427 | 12,2% |
| Peligroso | 910 | 7,8% |
| Bueno | 33 | 0,3% |
| **Total** | **11.710** | **100%** |

### **E) Top 5 departamentos por Tasa de Mortalidad General (TMG)**

| Departamento | TMG (x 100.000 hab.) | Total muertes | Población |
| :--- | ---: | ---: | ---: |
| Quindío (63) | 826,4 | 4.602 | 556.880 |
| Risaralda (66) | 800,4 | 7.987 | 997.930 |
| Valle del Cauca (76) | 685,2 | 32.159 | 4.693.432 |
| Tolima (73) | 656,5 | 9.063 | 1.380.444 |
| Caldas (17) | 646,9 | 6.794 | 1.050.126 |

### **F) Cobertura del catálogo CIE-10**

| Métrica | Valor |
| :--- | :--- |
| Códigos en catálogo `diagnostico_cie10` | 123 |
| Defunciones cubiertas por el catálogo | 155.742 / 275.778 |
| Porcentaje de cobertura | 56,5% |
| Diagnóstico más frecuente | I219 – Infarto agudo de miocardio (41.726 casos) |
| 2° más frecuente | J440 – EPOC con infección respiratoria aguda (8.052 casos) |
| 3° más frecuente | J449 – EPOC no especificada (5.751 casos) |

> **Nota sobre la cobertura:** El 43,5% de los códigos CIE-10 del dataset no están en el catálogo porque corresponden a diagnósticos fuera del foco del estudio (causas externas, enfermedades no relacionadas con calidad del aire, etc.). Los códigos respiratorios y cardiovasculares están cubiertos en su totalidad.

##  **1.3. Cargar de datos**

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

### **A) Estructura de la base de datos en MySQL**

La base de datos se denomina **`mortalidad_calidad_aire`** y se organiza en **13 tablas** siguiendo el modelo relacional descrito anteriormente. A continuación se presenta el esquema de creación con sus llaves primarias, foráneas y tipos de datos.

**Tablas de dimensión (catálogos y referencias):**

```sql
CREATE DATABASE mortalidad_calidad_aire;
USE mortalidad_calidad_aire;

-- ─────────────────────────────────────────
-- DIMENSIÓN: pais
-- ─────────────────────────────────────────
CREATE TABLE pais (
    id          VARCHAR(10)  NOT NULL,   -- Código M49 ONU
    nombre      VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

-- ─────────────────────────────────────────
-- DIMENSIÓN: departamento
-- ─────────────────────────────────────────
CREATE TABLE departamento (
    id      CHAR(2)      NOT NULL,   -- Código DIVIPOLA 2 dígitos
    nombre  VARCHAR(100) NOT NULL,
    region  VARCHAR(50)  NOT NULL,
    PRIMARY KEY (id)
);

-- ─────────────────────────────────────────
-- DIMENSIÓN: municipio
-- ─────────────────────────────────────────
CREATE TABLE municipio (
    id               CHAR(5)       NOT NULL,   -- Código DIVIPOLA 5 dígitos
    id_departamento  CHAR(2)       NOT NULL,
    nombre           VARCHAR(100)  NOT NULL,
    poblacion        INT           NOT NULL,
    latitud          DECIMAL(9,6)  NOT NULL,
    longitud         DECIMAL(9,6)  NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_departamento) REFERENCES departamento(id)
);

-- ─────────────────────────────────────────
-- DIMENSIÓN: tiempo
-- ─────────────────────────────────────────
CREATE TABLE tiempo (
    id    INT NOT NULL AUTO_INCREMENT,
    anio  INT NOT NULL,
    mes   INT NOT NULL,
    PRIMARY KEY (id)
);

-- ─────────────────────────────────────────
-- DIMENSIÓN: diagnostico_cie10
-- ─────────────────────────────────────────
CREATE TABLE diagnostico_cie10 (
    id               VARCHAR(10)  NOT NULL,   -- Código CIE-10
    nombre           VARCHAR(200) NOT NULL,
    categoria        VARCHAR(100) NOT NULL,
    es_respiratorio  TINYINT(1)   NOT NULL,
    PRIMARY KEY (id)
);
```

**Tablas de hechos (datos transaccionales):**

```sql
-- ─────────────────────────────────────────
-- HECHO: persona
-- ─────────────────────────────────────────
CREATE TABLE persona (
    id                   BIGINT       NOT NULL,
    id_pais_nacimiento   VARCHAR(10),
    sexo                 TINYINT      NOT NULL,
    grupo_edad_1         TINYINT      NOT NULL,
    grupo_edad_2         TINYINT      NOT NULL,
    estado_civil         TINYINT      NOT NULL,
    nivel_educativo      TINYINT      NOT NULL,
    seguridad_social     TINYINT      NOT NULL,
    ocupacion            VARCHAR(200),
    PRIMARY KEY (id),
    FOREIGN KEY (id_pais_nacimiento) REFERENCES pais(id)
);

-- ─────────────────────────────────────────
-- HECHO: defuncion
-- ─────────────────────────────────────────
CREATE TABLE defuncion (
    id                        BIGINT      NOT NULL,
    id_persona                BIGINT      NOT NULL,
    id_tiempo                 INT         NOT NULL,
    id_municipio_ocurrencia   CHAR(5),
    id_municipio_residencia   CHAR(5),
    area_defuncion            TINYINT     NOT NULL,
    area_residencia           FLOAT,
    sitio_defuncion           TINYINT     NOT NULL,
    probable_manera_muerte    FLOAT,
    ocupacion_causa_muerte    FLOAT,
    tipo_accidente_laboral    TINYINT     NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_persona)              REFERENCES persona(id),
    FOREIGN KEY (id_tiempo)               REFERENCES tiempo(id),
    FOREIGN KEY (id_municipio_ocurrencia) REFERENCES municipio(id),
    FOREIGN KEY (id_municipio_residencia) REFERENCES municipio(id)
);

-- ─────────────────────────────────────────
-- HECHO: causa_defuncion
-- ─────────────────────────────────────────
CREATE TABLE causa_defuncion (
    id             BIGINT      NOT NULL,
    id_defuncion   BIGINT      NOT NULL,
    codigo_cie10   VARCHAR(10) NOT NULL,
    causa_ops_667  VARCHAR(10) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_defuncion) REFERENCES defuncion(id)
);

-- ─────────────────────────────────────────
-- HECHO: defuncion_diagnostico
-- ─────────────────────────────────────────
CREATE TABLE defuncion_diagnostico (
    id               BIGINT     NOT NULL AUTO_INCREMENT,
    id_defuncion     BIGINT     NOT NULL,
    id_diagnostico   VARCHAR(10) NOT NULL,
    es_causa_basica  TINYINT(1) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_defuncion)   REFERENCES defuncion(id),
    FOREIGN KEY (id_diagnostico) REFERENCES diagnostico_cie10(id)
);

-- ─────────────────────────────────────────
-- HECHO: estacion_monitoreo
-- ─────────────────────────────────────────
CREATE TABLE estacion_monitoreo (
    id                 INT          NOT NULL AUTO_INCREMENT,
    id_municipio       CHAR(5)      NOT NULL,
    nombre             VARCHAR(100) NOT NULL,
    latitud            DECIMAL(9,6) NOT NULL,
    longitud           DECIMAL(9,6) NOT NULL,
    altitud            FLOAT        NOT NULL,
    entidad_operadora  VARCHAR(50)  NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_municipio) REFERENCES municipio(id)
);

-- ─────────────────────────────────────────
-- HECHO: medicion_calidad_aire
-- ─────────────────────────────────────────
CREATE TABLE medicion_calidad_aire (
    id           INT     NOT NULL AUTO_INCREMENT,
    id_estacion  INT     NOT NULL,
    id_tiempo    INT     NOT NULL,
    pm25         FLOAT   NOT NULL,
    pm10         FLOAT   NOT NULL,
    no2          FLOAT   NOT NULL,
    so2          FLOAT   NOT NULL,
    co           FLOAT   NOT NULL,
    o3           FLOAT   NOT NULL,
    temperatura  FLOAT   NOT NULL,
    humedad      FLOAT   NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_estacion) REFERENCES estacion_monitoreo(id),
    FOREIGN KEY (id_tiempo)   REFERENCES tiempo(id)
);

-- ─────────────────────────────────────────
-- HECHO: indice_calidad_aire
-- ─────────────────────────────────────────
CREATE TABLE indice_calidad_aire (
    id            INT        NOT NULL AUTO_INCREMENT,
    id_medicion   INT        NOT NULL,
    id_estacion   INT        NOT NULL,
    id_tiempo     INT        NOT NULL,
    ica_pm25      FLOAT      NOT NULL,
    ica_pm10      FLOAT      NOT NULL,
    ica_no2       FLOAT      NOT NULL,
    ica_so2       FLOAT      NOT NULL,
    ica_co        FLOAT      NOT NULL,
    ica_o3        FLOAT      NOT NULL,
    ica_general   FLOAT      NOT NULL,
    nivel_riesgo  VARCHAR(40) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_medicion)  REFERENCES medicion_calidad_aire(id),
    FOREIGN KEY (id_estacion)  REFERENCES estacion_monitoreo(id),
    FOREIGN KEY (id_tiempo)    REFERENCES tiempo(id)
);

-- ─────────────────────────────────────────
-- HECHO: tasa_mortalidad
-- ─────────────────────────────────────────
CREATE TABLE tasa_mortalidad (
    id                INT          NOT NULL AUTO_INCREMENT,
    id_tiempo         INT          NOT NULL,
    nivel_geografico  VARCHAR(20)  NOT NULL,   -- 'municipio' o 'departamento'
    id_geografia      VARCHAR(10)  NOT NULL,   -- Código DIVIPOLA
    tipo_tasa         VARCHAR(10)  NOT NULL,   -- TMG, TMCE, TMAE, AVPP
    causa             VARCHAR(20)  NOT NULL,   -- 'TODAS' o 'RESPIRATORIA'
    valor             DOUBLE       NOT NULL,
    poblacion_base    INT          NOT NULL,
    total_muertes     INT          NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_tiempo) REFERENCES tiempo(id)
);
```

**Orden de inserción recomendado** (respetando dependencias de FK):

```
1. pais              5. tiempo               9.  medicion_calidad_aire
2. departamento      6. diagnostico_cie10    10. indice_calidad_aire
3. municipio         7. persona              11. causa_defuncion
4. estacion_monitoreo 8. defuncion           12. defuncion_diagnostico
                                             13. tasa_mortalidad
```

# **Resultados Esperados**

Con base en el diseño de la base de datos, las fuentes de información integradas y el marco teórico del proyecto, se anticipan los siguientes resultados al completar el análisis:

## **1. Correlación entre ICA y tasa de mortalidad respiratoria**

Se espera identificar una **correlación positiva estadísticamente significativa** entre el Índice de Calidad del Aire (ICA) promedio por departamento y la Tasa de Mortalidad por Causa Específica Respiratoria (TMCE). Departamentos con niveles promedio de ICA clasificados como 'Dañino' o 'Muy dañino' deberían presentar tasas de mortalidad respiratoria superiores al promedio nacional.

## **2. Identificación de departamentos críticos**

Se espera que el análisis permita identificar **al menos 5 departamentos** con simultaneidad de alta carga de contaminantes (PM2.5, PM10) y alta mortalidad por causas respiratorias (EPOC, neumonías, J44x, J18x). Con base en los resultados preliminares del ETL, el Eje Cafetero (Quindío, Risaralda, Caldas) y la región Pacífica se perfilan como zonas de interés prioritario.

## **3. Patrones temporales de mortalidad**

A través de la dimensión `tiempo` (48 combinaciones año-mes), se espera detectar **variaciones estacionales** en la mortalidad respiratoria vinculadas a períodos de mayor concentración de contaminantes, particularmente en los meses de menor precipitación (enero-febrero y julio-agosto en Colombia).

## **4. Perfil sociodemográfico del fallecido**

Integrando las tablas `persona` y `defuncion_diagnostico`, se espera caracterizar el **perfil de mayor vulnerabilidad**: adultos mayores (grupo_edad_1 = 3), con bajo nivel educativo, afiliados al régimen subsidiado, residentes en áreas rurales (area_residencia = 3), con diagnóstico primario de EPOC (J44x) o neumonía (J18x).

## **5. Indicadores para el dashboard**

El dashboard final deberá permitir visualizar, como mínimo:

| Visualización | Tipo | Variables involucradas |
| :--- | :--- | :--- |
| Mapa coroplético de TMCE por departamento | Mapa | `tasa_mortalidad`, `departamento` |
| Evolución mensual del ICA general | Línea | `indice_calidad_aire`, `tiempo` |
| Scatter ICA vs TMCE por departamento | Dispersión | `indice_calidad_aire`, `tasa_mortalidad` |
| Top 10 causas de muerte respiratoria | Barras | `defuncion_diagnostico`, `diagnostico_cie10` |
| Distribución de nivel de riesgo ICA | Torta/Dona | `indice_calidad_aire` |

## **6. Recomendaciones esperadas**

Con base en los hallazgos, se anticipa que el proyecto pueda fundamentar recomendaciones dirigidas a:
- Priorizar intervenciones de control de fuentes de PM2.5 en los departamentos del Eje Cafetero.
- Fortalecer la red de estaciones de monitoreo en municipios con alta TMCE y sin cobertura actual del IDEAM.
- Revisar los umbrales permisibles de la Resolución 2254/2017 frente a la evidencia epidemiológica de 2024.
- Focalizar programas de salud respiratoria en adultos mayores del régimen subsidiado en zonas de alto ICA.